#include <config.h>
/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "lock_protocol.h"
#include "internal.h"
#include "lock_driver_lockd.h"

bool_t
xdr_virLockSpaceProtocolUUID (XDR *xdrs, virLockSpaceProtocolUUID objp)
{

         if (!xdr_opaque (xdrs, objp, VIR_UUID_BUFLEN))
                 return FALSE;
        return TRUE;
}

bool_t
xdr_virLockSpaceProtocolNonNullString (XDR *xdrs, virLockSpaceProtocolNonNullString *objp)
{

         if (!xdr_string (xdrs, objp, VIR_LOCK_SPACE_PROTOCOL_STRING_MAX))
                 return FALSE;
        return TRUE;
}

bool_t
xdr_virLockSpaceProtocolString (XDR *xdrs, virLockSpaceProtocolString *objp)
{

         if (!xdr_pointer (xdrs, (char **)objp, sizeof (virLockSpaceProtocolNonNullString), (xdrproc_t) xdr_virLockSpaceProtocolNonNullString))
                 return FALSE;
        return TRUE;
}

bool_t
xdr_virLockSpaceProtocolOwner (XDR *xdrs, virLockSpaceProtocolOwner *objp)
{

         if (!xdr_virLockSpaceProtocolUUID (xdrs, objp->uuid))
                 return FALSE;
         if (!xdr_virLockSpaceProtocolNonNullString (xdrs, &objp->name))
                 return FALSE;
         if (!xdr_u_int (xdrs, &objp->id))
                 return FALSE;
         if (!xdr_u_int (xdrs, &objp->pid))
                 return FALSE;
        return TRUE;
}

bool_t
xdr_virLockSpaceProtocolRegisterArgs (XDR *xdrs, virLockSpaceProtocolRegisterArgs *objp)
{

         if (!xdr_virLockSpaceProtocolOwner (xdrs, &objp->owner))
                 return FALSE;
         if (!xdr_u_int (xdrs, &objp->flags))
                 return FALSE;
        return TRUE;
}

bool_t
xdr_virLockSpaceProtocolRestrictArgs (XDR *xdrs, virLockSpaceProtocolRestrictArgs *objp)
{

         if (!xdr_u_int (xdrs, &objp->flags))
                 return FALSE;
        return TRUE;
}

bool_t
xdr_virLockSpaceProtocolNewArgs (XDR *xdrs, virLockSpaceProtocolNewArgs *objp)
{

         if (!xdr_virLockSpaceProtocolNonNullString (xdrs, &objp->path))
                 return FALSE;
         if (!xdr_u_int (xdrs, &objp->flags))
                 return FALSE;
        return TRUE;
}

bool_t
xdr_virLockSpaceProtocolCreateResourceArgs (XDR *xdrs, virLockSpaceProtocolCreateResourceArgs *objp)
{

         if (!xdr_virLockSpaceProtocolNonNullString (xdrs, &objp->path))
                 return FALSE;
         if (!xdr_virLockSpaceProtocolNonNullString (xdrs, &objp->name))
                 return FALSE;
         if (!xdr_u_int (xdrs, &objp->flags))
                 return FALSE;
        return TRUE;
}

bool_t
xdr_virLockSpaceProtocolDeleteResourceArgs (XDR *xdrs, virLockSpaceProtocolDeleteResourceArgs *objp)
{

         if (!xdr_virLockSpaceProtocolNonNullString (xdrs, &objp->path))
                 return FALSE;
         if (!xdr_virLockSpaceProtocolNonNullString (xdrs, &objp->name))
                 return FALSE;
         if (!xdr_u_int (xdrs, &objp->flags))
                 return FALSE;
        return TRUE;
}

bool_t
xdr_virLockSpaceProtocolAcquireResourceArgs (XDR *xdrs, virLockSpaceProtocolAcquireResourceArgs *objp)
{

         if (!xdr_virLockSpaceProtocolNonNullString (xdrs, &objp->path))
                 return FALSE;
         if (!xdr_virLockSpaceProtocolNonNullString (xdrs, &objp->name))
                 return FALSE;
         if (!xdr_u_int (xdrs, &objp->flags))
                 return FALSE;
        return TRUE;
}

bool_t
xdr_virLockSpaceProtocolReleaseResourceArgs (XDR *xdrs, virLockSpaceProtocolReleaseResourceArgs *objp)
{

         if (!xdr_virLockSpaceProtocolNonNullString (xdrs, &objp->path))
                 return FALSE;
         if (!xdr_virLockSpaceProtocolNonNullString (xdrs, &objp->name))
                 return FALSE;
         if (!xdr_u_int (xdrs, &objp->flags))
                 return FALSE;
        return TRUE;
}

bool_t
xdr_virLockSpaceProtocolCreateLockSpaceArgs (XDR *xdrs, virLockSpaceProtocolCreateLockSpaceArgs *objp)
{

         if (!xdr_virLockSpaceProtocolNonNullString (xdrs, &objp->path))
                 return FALSE;
        return TRUE;
}

bool_t
xdr_virLockSpaceProtocolProcedure (XDR *xdrs, virLockSpaceProtocolProcedure *objp)
{

         if (!xdr_enum (xdrs, (enum_t *) objp))
                 return FALSE;
        return TRUE;
}
