/*
    CMake autogenerated config.h file. Do not edit!
*/

#undef SOCK_CLOEXEC
#undef SOCK_NONBLOCK

#undef O_NONBLOCK
#undef FD_CLOEXEC


/* Package details */
#define LIGHTTPD_VERSION_ID 0x10475
#define PACKAGE_NAME "lighttpd"
#define PACKAGE_VERSION "1.4.75"
#define LIBRARY_DIR "/usr/local/lib/lighttpd"

#ifndef _GNU_SOURCE
# define _GNU_SOURCE
#endif

/* System */
#define  HAVE_DLFCN_H
#define  HAVE_GETOPT_H
#define  HAVE_INTTYPES_H
/* #undef HAVE_LINUX_RANDOM_H */
/* #undef HAVE_MALLOC_H */
#define  HAVE_POLL_H
/* #undef HAVE_PORT_H */
/* #undef HAVE_PRIV_H */
#define  HAVE_PWD_H
#define  HAVE_STDINT_H
#define  HAVE_STDLIB_H
#define  HAVE_STRINGS_H
#define  HAVE_SYSLOG_H
/* #undef HAVE_SYS_DEVPOLL_H */
/* #undef HAVE_SYS_EPOLL_H */
//#define  HAVE_SYS_EVENT_H
/* #undef HAVE_SYS_FILIO_H */
/* #undef HAVE_SYS_LOADAVG_H */
#define  HAVE_SYS_MMAN_H
#define  HAVE_SYS_POLL_H
/* #undef HAVE_SYS_PRCTL_H */
/* #undef HAVE_SYS_PROCCTL_H */
#define  HAVE_SYS_RESOURCE_H
/* #undef HAVE_SYS_SENDFILE_H */
/* #undef HAVE_SYS_SELECT_H */
#define  HAVE_SYS_TYPES_H
#define  HAVE_SYS_UIO_H
#define  HAVE_SYS_UN_H
#define  HAVE_SYS_WAIT_H
#define  HAVE_SYS_TIME_H
#define  HAVE_UNISTD_H

#define HAVE_IPV6
#define HAVE_STRUCT_TM_GMTOFF
#define HAVE_WEAK_SYMBOLS

/* XATTR */
/* #undef HAVE_ATTR_ATTRIBUTES_H */
/* #undef HAVE_SYS_XATTR_H */
/* #undef HAVE_XATTR */
/* #undef HAVE_SYS_EXTATTR_H */
/* #undef HAVE_EXTATTR */

/* xxHash */
/* #undef HAVE_XXHASH_H */

/* DBI */
/* #undef HAVE_DBI */

/* mySQL */
/* #undef HAVE_MYSQL */

/* PostreSQL */
/* #undef HAVE_PGSQL */

/* GnuTLS */
/* #undef HAVE_GNUTLS_CRYPTO_H */

/* mbedTLS */
/* #undef HAVE_MBEDCRYPTO */

/* Nettle */
/* #undef HAVE_NETTLE_NETTLE_TYPES_H */

/* NSS */
/* #undef HAVE_NSS_NSS_H */
/* #undef HAVE_NSS3_NSS_H */

/* OpenSSL */
/* #undef HAVE_OPENSSL_SSL_H */
/* #undef HAVE_LIBSSL */

/* wolfSSL */
/* #undef HAVE_WOLFSSL_SSL_H */

/* Brotli */
/* #undef HAVE_BROTLI */
/* #undef HAVE_BROTLI_ENCODE_H */

/* BZip */
/* #undef HAVE_BZLIB_H */
/* #undef HAVE_LIBBZ2 */

/* ZStd */
/* #undef HAVE_ZSTD */
/* #undef HAVE_ZSTD_H */

/* libdeflate */
/* #undef HAVE_LIBDEFLATE */

/* FAM */
/* #undef HAVE_FAM_H */
/* #undef HAVE_FAMNOEXISTS */

/* Kerberos5 */
/* #undef HAVE_KRB5 */

/* LDAP */
/* #undef HAVE_LDAP_H */
/* #undef HAVE_LIBLDAP */
/* #undef HAVE_LBER_H */
/* #undef HAVE_LIBLBER */

/* PAM */
/* #undef HAVE_PAM */

/* XML */
/* #undef HAVE_LIBXML_H */
/* #undef HAVE_LIBXML2 */

/* PCRE */
//#define  HAVE_PCRE
/* #undef HAVE_PCRE_H */
//#define  HAVE_PCRE2_H

/* sqlite3 */
/* #undef HAVE_SQLITE3_H */

/* ZLIB */
#define  HAVE_ZLIB_H
#define  HAVE_LIBZ

/* lua */
/* #undef HAVE_LUA_H */

/* inotify */
/* #undef HAVE_INOTIFY_INIT */
/* #undef HAVE_SYS_INOTIFY_H */

/* Types */
#define  HAVE_SOCKLEN_T
#define  SIZEOF_LONG 8
#define  SIZEOF_OFF_T 8

/* Functions */
//#define  HAVE_ARC4RANDOM_BUF
//#define  HAVE_CHROOT
#define  HAVE_CLOCK_GETTIME
/* #undef HAVE_ELFTC_COPYFILE */
/* #undef HAVE_EPOLL_CTL */
//#define  HAVE_FORK
#define  HAVE_GETENTROPY
#define  HAVE_GETLOADAVG
/* #undef HAVE_GETRANDOM */
#define  HAVE_GETRLIMIT
#define  HAVE_GETUID
#define  HAVE_GMTIME_R
#define  HAVE_INET_ATON
#define  HAVE_INET_PTON
#define  HAVE_JRAND48
#define  HAVE_KQUEUE
#define  HAVE_LOCALTIME_R
#define  HAVE_LSTAT
#define  HAVE_MADVISE
/* #undef HAVE_MALLOC_TRIM */
/* #undef HAVE_MALLOPT */
/* #undef HAVE_MEMPCPY */
#define  HAVE_MKOSTEMP
//#define  HAVE_MMAP
/* #undef HAVE_PIPE2 */
#define  HAVE_POLL
//#define  HAVE_POSIX_SPAWN
/* #undef HAVE_POSIX_SPAWN_FILE_ACTIONS_ADDCLOSEFROM_NP */
#define  HAVE_POSIX_SPAWN_FILE_ACTIONS_ADDFCHDIR_NP
/* #undef HAVE_PORT_CREATE */
#define  HAVE_PREAD
//#define  HAVE_PREADV
/* #undef HAVE_PREADV2 */
#define  HAVE_PWRITE
//#define  HAVE_PWRITEV
/* #undef HAVE_SELECT */
#define  HAVE_SENDFILE
/* #undef HAVE_SEND_FILE */
/* #undef HAVE_SENDFILEV */
/* #undef HAVE_SETPFLAGS */
//#define  HAVE_SIGACTION
//#define  HAVE_SIGNAL
/* #undef HAVE_SIGTIMEDWAIT */
/* #undef HAVE_SPLICE */
#define  HAVE_SRANDOM
#define  HAVE_STRERROR_R
#define  HAVE_TIMEGM
//#define  HAVE_WRITEV
#define  HAVE_ISSETUGID
//#define  HAVE_MEMSET_S
/* #undef HAVE_EXPLICIT_BZERO */
/* #undef HAVE_EXPLICIT_MEMSET */
/* #undef HAVE_COPY_FILE_RANGE */

/* libcrypt */
/* #undef HAVE_CRYPT_H */
#define  HAVE_CRYPT
/* #undef HAVE_CRYPT_R */

/* libunwind */
/* #undef HAVE_LIBUNWIND */

#define LIGHTTPD_STATIC
