/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _VIRKEEPALIVEPROTOCOL_H_RPCGEN
#define _VIRKEEPALIVEPROTOCOL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define KEEPALIVE_PROGRAM 0x6b656570
#define KEEPALIVE_PROTOCOL_VERSION 1

enum keepalive_procedure {
        KEEPALIVE_PROC_PING = 1,
        KEEPALIVE_PROC_PONG = 2,
};
typedef enum keepalive_procedure keepalive_procedure;

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_keepalive_procedure (XDR *, keepalive_procedure*);

#else /* K&R C */
extern bool_t xdr_keepalive_procedure ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_VIRKEEPALIVEPROTOCOL_H_RPCGEN */
