/* Automatically generated from ../.././src/remote/qemu_protocol.x by gendispatch.pl.
 * Do not edit this file.  Any changes you make will be lost.
 */
#include "internal.h"
#include "domain_conf.h"
#include "network_conf.h"
#include "secret_conf.h"
#include "storage_conf.h"
#include "nwfilter_conf.h"
#include "node_device_conf.h"
#include "interface_conf.h"
#include "virnwfilterbindingdef.h"

extern int virConnectDomainQemuMonitorEventDeregisterEnsureACL(virConnectPtr conn);
extern int virConnectDomainQemuMonitorEventRegisterEnsureACL(virConnectPtr conn);
extern bool virConnectDomainQemuMonitorEventRegisterCheckACL(virConnectPtr conn, virDomainDefPtr domain);
extern int virDomainQemuAgentCommandEnsureACL(virConnectPtr conn, virDomainDefPtr domain);
extern int virDomainQemuAttachEnsureACL(virConnectPtr conn, virDomainDefPtr domain);
extern int virDomainQemuMonitorCommandEnsureACL(virConnectPtr conn, virDomainDefPtr domain);
