/* Automatically generated from ../.././src/remote/lxc_protocol.x by gendispatch.pl.
 * Do not edit this file.  Any changes you make will be lost.
 */
#include "internal.h"
#include "domain_conf.h"
#include "network_conf.h"
#include "secret_conf.h"
#include "storage_conf.h"
#include "nwfilter_conf.h"
#include "node_device_conf.h"
#include "interface_conf.h"
#include "virnwfilterbindingdef.h"

extern int virDomainLxcOpenNamespaceEnsureACL(virConnectPtr conn, virDomainDefPtr domain);
