## DO NOT EDIT! GENERATED AUTOMATICALLY!
## Process this file with automake to produce Makefile.in.
# Copyright (C) 2002-2018 Free Software Foundation, Inc.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this file.  If not, see <https://www.gnu.org/licenses/>.
#
# As a special exception to the GNU General Public License,
# this file may be distributed as part of a program that
# contains a configuration script generated by Autoconf, under
# the same distribution terms as the rest of that program.
#
# Generated by gnulib-tool.

AUTOMAKE_OPTIONS = 1.9.6 foreign subdir-objects

SUBDIRS = .
GNULIB_TESTS =
XFAIL_TESTS =
TESTS_ENVIRONMENT =
noinst_PROGRAMS =
check_PROGRAMS =
EXTRA_PROGRAMS =
noinst_HEADERS =
noinst_LIBRARIES =
check_LIBRARIES = libtests.a
EXTRA_DIST =
BUILT_SOURCES =
SUFFIXES =
MOSTLYCLEANFILES = core *.stackdump
MOSTLYCLEANDIRS =
CLEANFILES =
DISTCLEANFILES =
MAINTAINERCLEANFILES =

AM_CPPFLAGS = \
  -D@gltests_WITNESS@=1 \
  -I. -I$(srcdir) \
  -I../.. -I$(srcdir)/../.. \
  -I../../gnulib/lib -I$(srcdir)/../../gnulib/lib

LDADD = libtests.a ../../gnulib/lib/libgnu.la libtests.a $(LIBTESTS_LIBDEPS)

libtests_a_SOURCES =
libtests_a_LIBADD = $(gltests_LIBOBJS)
libtests_a_DEPENDENCIES = $(gltests_LIBOBJS)
EXTRA_libtests_a_SOURCES =
AM_LIBTOOLFLAGS = --preserve-dup-deps

TESTS_ENVIRONMENT += EXEEXT='@EXEEXT@' srcdir='$(srcdir)'

## begin gnulib module accept-tests

GNULIB_TESTS += test-accept
check_PROGRAMS += test-accept
test_accept_LDADD = $(LDADD) @LIBSOCKET@
EXTRA_DIST += test-accept.c signature.h macros.h

## end   gnulib module accept-tests

## begin gnulib module alloca-opt-tests

GNULIB_TESTS += test-alloca-opt
check_PROGRAMS += test-alloca-opt

EXTRA_DIST += test-alloca-opt.c

## end   gnulib module alloca-opt-tests

## begin gnulib module areadlink-tests

GNULIB_TESTS += test-areadlink
check_PROGRAMS += test-areadlink
EXTRA_DIST += test-areadlink.h test-areadlink.c macros.h

## end   gnulib module areadlink-tests

## begin gnulib module arpa_inet-tests

GNULIB_TESTS += test-arpa_inet
check_PROGRAMS += test-arpa_inet
EXTRA_DIST += test-arpa_inet.c

## end   gnulib module arpa_inet-tests

## begin gnulib module base64-tests

GNULIB_TESTS += test-base64
check_PROGRAMS += test-base64
EXTRA_DIST += test-base64.c macros.h

## end   gnulib module base64-tests

## begin gnulib module binary-io-tests

GNULIB_TESTS += test-binary-io.sh
check_PROGRAMS += test-binary-io

EXTRA_DIST += test-binary-io.sh test-binary-io.c macros.h

## end   gnulib module binary-io-tests

## begin gnulib module bind-tests

GNULIB_TESTS += test-bind
check_PROGRAMS += test-bind
test_bind_LDADD = $(LDADD) @LIBSOCKET@ $(INET_PTON_LIB)
EXTRA_DIST += test-bind.c signature.h macros.h

## end   gnulib module bind-tests

## begin gnulib module bitrotate-tests

GNULIB_TESTS += test-bitrotate
check_PROGRAMS += test-bitrotate
EXTRA_DIST += test-bitrotate.c macros.h

## end   gnulib module bitrotate-tests

## begin gnulib module btowc-tests

GNULIB_TESTS += test-btowc1.sh test-btowc2.sh
TESTS_ENVIRONMENT += LOCALE_FR='@LOCALE_FR@' LOCALE_FR_UTF8='@LOCALE_FR_UTF8@'
check_PROGRAMS += test-btowc

EXTRA_DIST += test-btowc1.sh test-btowc2.sh test-btowc.c signature.h macros.h

## end   gnulib module btowc-tests

## begin gnulib module byteswap-tests

GNULIB_TESTS += test-byteswap
check_PROGRAMS += test-byteswap
EXTRA_DIST += test-byteswap.c macros.h

## end   gnulib module byteswap-tests

## begin gnulib module c-ctype-tests

GNULIB_TESTS += test-c-ctype
check_PROGRAMS += test-c-ctype
EXTRA_DIST += test-c-ctype.c macros.h

## end   gnulib module c-ctype-tests

## begin gnulib module c-strcase-tests

GNULIB_TESTS += test-c-strcase.sh
TESTS_ENVIRONMENT += LOCALE_FR='@LOCALE_FR@' LOCALE_TR_UTF8='@LOCALE_TR_UTF8@'
check_PROGRAMS += test-c-strcasecmp test-c-strncasecmp
EXTRA_DIST += test-c-strcase.sh test-c-strcasecmp.c test-c-strncasecmp.c macros.h

## end   gnulib module c-strcase-tests

## begin gnulib module c-strcasestr-tests

GNULIB_TESTS += test-c-strcasestr
check_PROGRAMS += test-c-strcasestr

EXTRA_DIST += test-c-strcasestr.c macros.h

## end   gnulib module c-strcasestr-tests

## begin gnulib module canonicalize-lgpl-tests

GNULIB_TESTS += test-canonicalize-lgpl
check_PROGRAMS += test-canonicalize-lgpl
EXTRA_DIST += test-canonicalize-lgpl.c signature.h null-ptr.h macros.h

## end   gnulib module canonicalize-lgpl-tests

## begin gnulib module chown-tests

GNULIB_TESTS += test-chown
check_PROGRAMS += test-chown
test_chown_LDADD = $(LDADD) $(LIB_NANOSLEEP)
EXTRA_DIST += nap.h test-chown.h test-chown.c signature.h macros.h

## end   gnulib module chown-tests

## begin gnulib module cloexec-tests

GNULIB_TESTS += test-cloexec
check_PROGRAMS += test-cloexec
EXTRA_DIST += test-cloexec.c macros.h

## end   gnulib module cloexec-tests

## begin gnulib module close-tests

GNULIB_TESTS += test-close
check_PROGRAMS += test-close
EXTRA_DIST += test-close.c signature.h macros.h

## end   gnulib module close-tests

## begin gnulib module connect-tests

GNULIB_TESTS += test-connect
check_PROGRAMS += test-connect
test_connect_LDADD = $(LDADD) @LIBSOCKET@ $(INET_PTON_LIB)
EXTRA_DIST += test-connect.c signature.h macros.h

## end   gnulib module connect-tests

## begin gnulib module count-leading-zeros-tests

GNULIB_TESTS += test-count-leading-zeros
check_PROGRAMS += test-count-leading-zeros
EXTRA_DIST += test-count-leading-zeros.c macros.h

## end   gnulib module count-leading-zeros-tests

## begin gnulib module count-one-bits-tests

GNULIB_TESTS += test-count-one-bits
check_PROGRAMS += test-count-one-bits
EXTRA_DIST += test-count-one-bits.c macros.h

## end   gnulib module count-one-bits-tests

## begin gnulib module ctype

BUILT_SOURCES += ctype.h

# We need the following in order to create <ctype.h> when the system
# doesn't have one that works with the given compiler.
ctype.h: ctype.in.h $(top_builddir)/config.status $(CXXDEFS_H) $(WARN_ON_USE_H)
	$(AM_V_GEN)rm -f $@-t $@ && \
	{ echo '/* DO NOT EDIT! GENERATED AUTOMATICALLY! */'; \
	  sed -e 's|@''GUARD_PREFIX''@|GL|g' \
	      -e 's|@''INCLUDE_NEXT''@|$(INCLUDE_NEXT)|g' \
	      -e 's|@''PRAGMA_SYSTEM_HEADER''@|@PRAGMA_SYSTEM_HEADER@|g' \
	      -e 's|@''PRAGMA_COLUMNS''@|@PRAGMA_COLUMNS@|g' \
	      -e 's|@''NEXT_CTYPE_H''@|$(NEXT_CTYPE_H)|g' \
	      -e 's/@''GNULIB_ISBLANK''@/$(GNULIB_ISBLANK)/g' \
	      -e 's/@''HAVE_ISBLANK''@/$(HAVE_ISBLANK)/g' \
	      -e '/definitions of _GL_FUNCDECL_RPL/r $(CXXDEFS_H)' \
	      -e '/definition of _GL_WARN_ON_USE/r $(WARN_ON_USE_H)' \
	      < $(srcdir)/ctype.in.h; \
	} > $@-t && \
	mv $@-t $@
MOSTLYCLEANFILES += ctype.h ctype.h-t

EXTRA_DIST += ctype.in.h

## end   gnulib module ctype

## begin gnulib module ctype-tests

GNULIB_TESTS += test-ctype
check_PROGRAMS += test-ctype
EXTRA_DIST += test-ctype.c

## end   gnulib module ctype-tests

## begin gnulib module dup


EXTRA_DIST += dup.c

EXTRA_libtests_a_SOURCES += dup.c

## end   gnulib module dup

## begin gnulib module dup-tests

GNULIB_TESTS += test-dup
check_PROGRAMS += test-dup
EXTRA_DIST += test-dup.c signature.h macros.h

## end   gnulib module dup-tests

## begin gnulib module dup2-tests

GNULIB_TESTS += test-dup2
check_PROGRAMS += test-dup2
EXTRA_DIST += test-dup2.c signature.h macros.h

## end   gnulib module dup2-tests

## begin gnulib module environ-tests

GNULIB_TESTS += test-environ
check_PROGRAMS += test-environ

EXTRA_DIST += test-environ.c

## end   gnulib module environ-tests

## begin gnulib module errno-tests

GNULIB_TESTS += test-errno
check_PROGRAMS += test-errno

EXTRA_DIST += test-errno.c

## end   gnulib module errno-tests

## begin gnulib module error


EXTRA_DIST += error.c error.h

EXTRA_libtests_a_SOURCES += error.c

## end   gnulib module error

## begin gnulib module exitfail

libtests_a_SOURCES += exitfail.c

EXTRA_DIST += exitfail.h

## end   gnulib module exitfail

## begin gnulib module fatal-signal

libtests_a_SOURCES += fatal-signal.h fatal-signal.c

## end   gnulib module fatal-signal

## begin gnulib module fclose-tests

GNULIB_TESTS += test-fclose
check_PROGRAMS += test-fclose
EXTRA_DIST += test-fclose.c

## end   gnulib module fclose-tests

## begin gnulib module fcntl-h-tests

GNULIB_TESTS += test-fcntl-h
check_PROGRAMS += test-fcntl-h
EXTRA_DIST += test-fcntl-h.c

## end   gnulib module fcntl-h-tests

## begin gnulib module fcntl-tests

GNULIB_TESTS += test-fcntl
check_PROGRAMS += test-fcntl
EXTRA_DIST += test-fcntl.c signature.h macros.h

## end   gnulib module fcntl-tests

## begin gnulib module fdatasync-tests

GNULIB_TESTS += test-fdatasync
check_PROGRAMS += test-fdatasync
test_fdatasync_LDADD = $(LDADD) $(LIB_FDATASYNC)
EXTRA_DIST += test-fdatasync.c signature.h macros.h

## end   gnulib module fdatasync-tests

## begin gnulib module fdopen


EXTRA_DIST += fdopen.c

EXTRA_libtests_a_SOURCES += fdopen.c

## end   gnulib module fdopen

## begin gnulib module fdopen-tests

GNULIB_TESTS += test-fdopen
check_PROGRAMS += test-fdopen
EXTRA_DIST += test-fdopen.c signature.h macros.h

## end   gnulib module fdopen-tests

## begin gnulib module fflush-tests

GNULIB_TESTS += test-fflush test-fflush2.sh
check_PROGRAMS += test-fflush test-fflush2
MOSTLYCLEANFILES += test-fflush.txt
EXTRA_DIST += test-fflush.c test-fflush2.sh test-fflush2.c signature.h macros.h

## end   gnulib module fflush-tests

## begin gnulib module ffs-tests

GNULIB_TESTS += test-ffs
check_PROGRAMS += test-ffs
EXTRA_DIST += test-ffs.c macros.h signature.h

## end   gnulib module ffs-tests

## begin gnulib module ffsl-tests

GNULIB_TESTS += test-ffsl
check_PROGRAMS += test-ffsl
EXTRA_DIST += test-ffsl.c macros.h signature.h

## end   gnulib module ffsl-tests

## begin gnulib module fgetc-tests

GNULIB_TESTS += test-fgetc
check_PROGRAMS += test-fgetc
EXTRA_DIST += test-fgetc.c signature.h macros.h

## end   gnulib module fgetc-tests

## begin gnulib module float-tests

GNULIB_TESTS += test-float
check_PROGRAMS += test-float
EXTRA_DIST += test-float.c macros.h

## end   gnulib module float-tests

## begin gnulib module fnmatch-tests

GNULIB_TESTS += test-fnmatch
check_PROGRAMS += test-fnmatch
EXTRA_DIST += test-fnmatch.c signature.h macros.h

## end   gnulib module fnmatch-tests

## begin gnulib module fpucw


EXTRA_DIST += fpucw.h

## end   gnulib module fpucw

## begin gnulib module fpurge-tests

GNULIB_TESTS += test-fpurge
check_PROGRAMS += test-fpurge
MOSTLYCLEANFILES += t-fpurge.tmp
EXTRA_DIST += test-fpurge.c macros.h

## end   gnulib module fpurge-tests

## begin gnulib module fputc-tests

GNULIB_TESTS += test-fputc
check_PROGRAMS += test-fputc
EXTRA_DIST += test-fputc.c signature.h macros.h

## end   gnulib module fputc-tests

## begin gnulib module fread-tests

GNULIB_TESTS += test-fread
check_PROGRAMS += test-fread
EXTRA_DIST += test-fread.c signature.h macros.h

## end   gnulib module fread-tests

## begin gnulib module freading-tests

GNULIB_TESTS += test-freading
check_PROGRAMS += test-freading
MOSTLYCLEANFILES += t-freading.tmp
EXTRA_DIST += test-freading.c macros.h

## end   gnulib module freading-tests

## begin gnulib module fseek-tests

GNULIB_TESTS += test-fseek.sh test-fseek2.sh
check_PROGRAMS += test-fseek
EXTRA_DIST += test-fseek.c test-fseek.sh test-fseek2.sh signature.h macros.h

## end   gnulib module fseek-tests

## begin gnulib module fseeko-tests

GNULIB_TESTS += test-fseeko.sh test-fseeko2.sh test-fseeko3.sh test-fseeko4.sh
check_PROGRAMS += test-fseeko test-fseeko3 test-fseeko4
EXTRA_DIST += test-fseeko.c test-fseeko.sh test-fseeko2.sh test-fseeko3.c test-fseeko3.sh test-fseeko4.c test-fseeko4.sh signature.h macros.h

## end   gnulib module fseeko-tests

## begin gnulib module fstat-tests

GNULIB_TESTS += test-fstat
check_PROGRAMS += test-fstat
EXTRA_DIST += test-fstat.c signature.h macros.h

## end   gnulib module fstat-tests

## begin gnulib module fsync-tests

GNULIB_TESTS += test-fsync
check_PROGRAMS += test-fsync
EXTRA_DIST += test-fsync.c signature.h macros.h

## end   gnulib module fsync-tests

## begin gnulib module ftell-tests

GNULIB_TESTS += test-ftell.sh test-ftell2.sh test-ftell3
check_PROGRAMS += test-ftell test-ftell3
MOSTLYCLEANFILES += t-ftell3.tmp
EXTRA_DIST += test-ftell.c test-ftell.sh test-ftell2.sh test-ftell3.c signature.h macros.h

## end   gnulib module ftell-tests

## begin gnulib module ftello-tests

GNULIB_TESTS += test-ftello.sh test-ftello2.sh test-ftello3 test-ftello4.sh
check_PROGRAMS += test-ftello test-ftello3 test-ftello4
MOSTLYCLEANFILES += t-ftello3.tmp
EXTRA_DIST += test-ftello.c test-ftello.sh test-ftello2.sh test-ftello3.c test-ftello4.c test-ftello4.sh signature.h macros.h

## end   gnulib module ftello-tests

## begin gnulib module ftruncate


EXTRA_DIST += ftruncate.c

EXTRA_libtests_a_SOURCES += ftruncate.c

## end   gnulib module ftruncate

## begin gnulib module ftruncate-tests

GNULIB_TESTS += test-ftruncate.sh
check_PROGRAMS += test-ftruncate
EXTRA_DIST += test-ftruncate.c test-ftruncate.sh signature.h macros.h

## end   gnulib module ftruncate-tests

## begin gnulib module func-tests

GNULIB_TESTS += test-func
check_PROGRAMS += test-func
EXTRA_DIST += test-func.c macros.h

## end   gnulib module func-tests

## begin gnulib module fwrite-tests

GNULIB_TESTS += test-fwrite
check_PROGRAMS += test-fwrite
EXTRA_DIST += test-fwrite.c signature.h macros.h

## end   gnulib module fwrite-tests

## begin gnulib module getaddrinfo-tests

GNULIB_TESTS += test-getaddrinfo
check_PROGRAMS += test-getaddrinfo
test_getaddrinfo_LDADD = $(LDADD) @GETADDRINFO_LIB@ @LIBINTL@
EXTRA_DIST += signature.h test-getaddrinfo.c

## end   gnulib module getaddrinfo-tests

## begin gnulib module getcwd-lgpl-tests

GNULIB_TESTS += test-getcwd-lgpl
check_PROGRAMS += test-getcwd-lgpl
test_getcwd_lgpl_LDADD = $(LDADD) $(LIBINTL)
EXTRA_DIST += test-getcwd-lgpl.c signature.h macros.h

## end   gnulib module getcwd-lgpl-tests

## begin gnulib module getdelim-tests

GNULIB_TESTS += test-getdelim
check_PROGRAMS += test-getdelim
MOSTLYCLEANFILES += test-getdelim.txt
EXTRA_DIST += test-getdelim.c signature.h macros.h

## end   gnulib module getdelim-tests

## begin gnulib module getdtablesize-tests

GNULIB_TESTS += test-getdtablesize
check_PROGRAMS += test-getdtablesize
EXTRA_DIST += test-getdtablesize.c signature.h macros.h

## end   gnulib module getdtablesize-tests

## begin gnulib module getgroups-tests

GNULIB_TESTS += test-getgroups
check_PROGRAMS += test-getgroups
EXTRA_DIST += test-getgroups.c signature.h macros.h

## end   gnulib module getgroups-tests

## begin gnulib module gethostname-tests

GNULIB_TESTS += test-gethostname
check_PROGRAMS += test-gethostname
test_gethostname_LDADD = $(LDADD) @GETHOSTNAME_LIB@
EXTRA_DIST += signature.h test-gethostname.c

## end   gnulib module gethostname-tests

## begin gnulib module getline-tests

GNULIB_TESTS += test-getline
check_PROGRAMS += test-getline
MOSTLYCLEANFILES += test-getline.txt
EXTRA_DIST += test-getline.c signature.h macros.h

## end   gnulib module getline-tests

## begin gnulib module getopt-posix-tests

GNULIB_TESTS += test-getopt-posix
check_PROGRAMS += test-getopt-posix
test_getopt_posix_LDADD = $(LDADD) $(LIBINTL)
EXTRA_DIST += macros.h signature.h test-getopt-posix.c test-getopt-main.h test-getopt.h

## end   gnulib module getopt-posix-tests

## begin gnulib module getpagesize


EXTRA_DIST += getpagesize.c

EXTRA_libtests_a_SOURCES += getpagesize.c

## end   gnulib module getpagesize

## begin gnulib module getpeername-tests

GNULIB_TESTS += test-getpeername
check_PROGRAMS += test-getpeername
test_getpeername_LDADD = $(LDADD) @LIBSOCKET@
EXTRA_DIST += test-getpeername.c signature.h macros.h

## end   gnulib module getpeername-tests

## begin gnulib module getprogname

libtests_a_SOURCES += getprogname.h getprogname.c

## end   gnulib module getprogname

## begin gnulib module getprogname-tests

DEFS += -DEXEEXT=\"@EXEEXT@\"
GNULIB_TESTS += test-getprogname
check_PROGRAMS += test-getprogname
test_getprogname_LDADD = $(LDADD)
EXTRA_DIST += test-getprogname.c

## end   gnulib module getprogname-tests

## begin gnulib module getsockname-tests

GNULIB_TESTS += test-getsockname
check_PROGRAMS += test-getsockname
test_getsockname_LDADD = $(LDADD) @LIBSOCKET@ $(INET_PTON_LIB)
EXTRA_DIST += test-getsockname.c signature.h macros.h

## end   gnulib module getsockname-tests

## begin gnulib module getsockopt


EXTRA_DIST += getsockopt.c w32sock.h

EXTRA_libtests_a_SOURCES += getsockopt.c

## end   gnulib module getsockopt

## begin gnulib module getsockopt-tests

GNULIB_TESTS += test-getsockopt
check_PROGRAMS += test-getsockopt
test_getsockopt_LDADD = $(LDADD) @LIBSOCKET@
EXTRA_DIST += test-getsockopt.c signature.h macros.h

## end   gnulib module getsockopt-tests

## begin gnulib module gettimeofday-tests

GNULIB_TESTS += test-gettimeofday
check_PROGRAMS += test-gettimeofday

EXTRA_DIST += signature.h test-gettimeofday.c

## end   gnulib module gettimeofday-tests

## begin gnulib module grantpt


EXTRA_DIST += grantpt.c pty-private.h

EXTRA_libtests_a_SOURCES += grantpt.c

## end   gnulib module grantpt

## begin gnulib module grantpt-tests

GNULIB_TESTS += test-grantpt
check_PROGRAMS += test-grantpt
EXTRA_DIST += test-grantpt.c signature.h macros.h

## end   gnulib module grantpt-tests

## begin gnulib module ignore-value-tests

GNULIB_TESTS += test-ignore-value
check_PROGRAMS += test-ignore-value
EXTRA_DIST += test-ignore-value.c

## end   gnulib module ignore-value-tests

## begin gnulib module inet_ntop-tests

GNULIB_TESTS += test-inet_ntop
check_PROGRAMS += test-inet_ntop
test_inet_ntop_LDADD = $(LDADD) @INET_NTOP_LIB@
EXTRA_DIST += test-inet_ntop.c signature.h macros.h

## end   gnulib module inet_ntop-tests

## begin gnulib module inet_pton-tests

GNULIB_TESTS += test-inet_pton
check_PROGRAMS += test-inet_pton
test_inet_pton_LDADD = $(LDADD) @INET_PTON_LIB@
EXTRA_DIST += test-inet_pton.c signature.h macros.h

## end   gnulib module inet_pton-tests

## begin gnulib module intprops-tests

GNULIB_TESTS += test-intprops
check_PROGRAMS += test-intprops
EXTRA_DIST += test-intprops.c macros.h

## end   gnulib module intprops-tests

## begin gnulib module inttypes-incomplete

BUILT_SOURCES += inttypes.h

# We need the following in order to create <inttypes.h> when the system
# doesn't have one that works with the given compiler.
inttypes.h: inttypes.in.h $(top_builddir)/config.status $(CXXDEFS_H) $(WARN_ON_USE_H) $(ARG_NONNULL_H)
	$(AM_V_GEN)rm -f $@-t $@ && \
	{ echo '/* DO NOT EDIT! GENERATED AUTOMATICALLY! */'; \
	  sed -e 's/@''HAVE_INTTYPES_H''@/$(HAVE_INTTYPES_H)/g' \
	      -e 's|@''INCLUDE_NEXT''@|$(INCLUDE_NEXT)|g' \
	      -e 's|@''PRAGMA_SYSTEM_HEADER''@|@PRAGMA_SYSTEM_HEADER@|g' \
	      -e 's|@''PRAGMA_COLUMNS''@|@PRAGMA_COLUMNS@|g' \
	      -e 's|@''NEXT_INTTYPES_H''@|$(NEXT_INTTYPES_H)|g' \
	      -e 's/@''PRI_MACROS_BROKEN''@/$(PRI_MACROS_BROKEN)/g' \
	      -e 's/@''APPLE_UNIVERSAL_BUILD''@/$(APPLE_UNIVERSAL_BUILD)/g' \
	      -e 's/@''HAVE_LONG_LONG_INT''@/$(HAVE_LONG_LONG_INT)/g' \
	      -e 's/@''HAVE_UNSIGNED_LONG_LONG_INT''@/$(HAVE_UNSIGNED_LONG_LONG_INT)/g' \
	      -e 's/@''PRIPTR_PREFIX''@/$(PRIPTR_PREFIX)/g' \
	      -e 's/@''GNULIB_IMAXABS''@/$(GNULIB_IMAXABS)/g' \
	      -e 's/@''GNULIB_IMAXDIV''@/$(GNULIB_IMAXDIV)/g' \
	      -e 's/@''GNULIB_STRTOIMAX''@/$(GNULIB_STRTOIMAX)/g' \
	      -e 's/@''GNULIB_STRTOUMAX''@/$(GNULIB_STRTOUMAX)/g' \
	      -e 's/@''HAVE_DECL_IMAXABS''@/$(HAVE_DECL_IMAXABS)/g' \
	      -e 's/@''HAVE_DECL_IMAXDIV''@/$(HAVE_DECL_IMAXDIV)/g' \
	      -e 's/@''HAVE_DECL_STRTOIMAX''@/$(HAVE_DECL_STRTOIMAX)/g' \
	      -e 's/@''HAVE_DECL_STRTOUMAX''@/$(HAVE_DECL_STRTOUMAX)/g' \
	      -e 's/@''HAVE_IMAXDIV_T''@/$(HAVE_IMAXDIV_T)/g' \
	      -e 's/@''REPLACE_STRTOIMAX''@/$(REPLACE_STRTOIMAX)/g' \
	      -e 's/@''REPLACE_STRTOUMAX''@/$(REPLACE_STRTOUMAX)/g' \
	      -e 's/@''INT32_MAX_LT_INTMAX_MAX''@/$(INT32_MAX_LT_INTMAX_MAX)/g' \
	      -e 's/@''INT64_MAX_EQ_LONG_MAX''@/$(INT64_MAX_EQ_LONG_MAX)/g' \
	      -e 's/@''UINT32_MAX_LT_UINTMAX_MAX''@/$(UINT32_MAX_LT_UINTMAX_MAX)/g' \
	      -e 's/@''UINT64_MAX_EQ_ULONG_MAX''@/$(UINT64_MAX_EQ_ULONG_MAX)/g' \
	      -e '/definitions of _GL_FUNCDECL_RPL/r $(CXXDEFS_H)' \
	      -e '/definition of _GL_ARG_NONNULL/r $(ARG_NONNULL_H)' \
	      -e '/definition of _GL_WARN_ON_USE/r $(WARN_ON_USE_H)' \
	      < $(srcdir)/inttypes.in.h; \
	} > $@-t && \
	mv $@-t $@
MOSTLYCLEANFILES += inttypes.h inttypes.h-t

EXTRA_DIST += inttypes.in.h

## end   gnulib module inttypes-incomplete

## begin gnulib module inttypes-tests

GNULIB_TESTS += test-inttypes
check_PROGRAMS += test-inttypes
EXTRA_DIST += test-inttypes.c

## end   gnulib module inttypes-tests

## begin gnulib module ioctl-tests

GNULIB_TESTS += test-ioctl
check_PROGRAMS += test-ioctl
EXTRA_DIST += test-ioctl.c signature.h macros.h

## end   gnulib module ioctl-tests

## begin gnulib module isatty-tests

GNULIB_TESTS += test-isatty
check_PROGRAMS += test-isatty
EXTRA_DIST += test-isatty.c signature.h macros.h

## end   gnulib module isatty-tests

## begin gnulib module isblank


EXTRA_DIST += isblank.c

EXTRA_libtests_a_SOURCES += isblank.c

## end   gnulib module isblank

## begin gnulib module isblank-tests

GNULIB_TESTS += test-isblank
check_PROGRAMS += test-isblank
EXTRA_DIST += test-isblank.c signature.h macros.h

## end   gnulib module isblank-tests

## begin gnulib module isnand-nolibm


EXTRA_DIST += float+.h isnan.c isnand-nolibm.h isnand.c

EXTRA_libtests_a_SOURCES += isnan.c isnand.c

## end   gnulib module isnand-nolibm

## begin gnulib module isnand-nolibm-tests

GNULIB_TESTS += test-isnand-nolibm
check_PROGRAMS += test-isnand-nolibm

EXTRA_DIST += test-isnand-nolibm.c test-isnand.h minus-zero.h infinity.h nan.h macros.h

## end   gnulib module isnand-nolibm-tests

## begin gnulib module isnanf-nolibm


EXTRA_DIST += float+.h isnan.c isnanf-nolibm.h isnanf.c

EXTRA_libtests_a_SOURCES += isnan.c isnanf.c

## end   gnulib module isnanf-nolibm

## begin gnulib module isnanf-nolibm-tests

GNULIB_TESTS += test-isnanf-nolibm
check_PROGRAMS += test-isnanf-nolibm

EXTRA_DIST += test-isnanf-nolibm.c test-isnanf.h minus-zero.h infinity.h nan.h macros.h

## end   gnulib module isnanf-nolibm-tests

## begin gnulib module isnanl-nolibm


EXTRA_DIST += float+.h isnan.c isnanl-nolibm.h isnanl.c

EXTRA_libtests_a_SOURCES += isnan.c isnanl.c

## end   gnulib module isnanl-nolibm

## begin gnulib module isnanl-nolibm-tests

GNULIB_TESTS += test-isnanl-nolibm
check_PROGRAMS += test-isnanl-nolibm

EXTRA_DIST += test-isnanl-nolibm.c test-isnanl.h minus-zero.h infinity.h nan.h macros.h

## end   gnulib module isnanl-nolibm-tests

## begin gnulib module langinfo-tests

GNULIB_TESTS += test-langinfo
check_PROGRAMS += test-langinfo
EXTRA_DIST += test-langinfo.c

## end   gnulib module langinfo-tests

## begin gnulib module ldexp-tests

GNULIB_TESTS += test-ldexp
check_PROGRAMS += test-ldexp
test_ldexp_SOURCES = test-ldexp.c randomd.c
test_ldexp_LDADD = $(LDADD) @LDEXP_LIBM@
EXTRA_DIST += test-ldexp.c test-ldexp.h minus-zero.h infinity.h nan.h signature.h macros.h randomd.c

## end   gnulib module ldexp-tests

## begin gnulib module limits-h-tests

GNULIB_TESTS += test-limits-h
check_PROGRAMS += test-limits-h
EXTRA_DIST += test-limits-h.c

## end   gnulib module limits-h-tests

## begin gnulib module listen-tests

GNULIB_TESTS += test-listen
check_PROGRAMS += test-listen
test_listen_LDADD = $(LDADD) @LIBSOCKET@
EXTRA_DIST += test-listen.c signature.h macros.h

## end   gnulib module listen-tests

## begin gnulib module localcharset-tests

noinst_PROGRAMS += test-localcharset
EXTRA_DIST += test-localcharset.c

## end   gnulib module localcharset-tests

## begin gnulib module locale-tests

GNULIB_TESTS += test-locale
check_PROGRAMS += test-locale
EXTRA_DIST += test-locale.c

## end   gnulib module locale-tests

## begin gnulib module localeconv-tests

GNULIB_TESTS += test-localeconv
check_PROGRAMS += test-localeconv
EXTRA_DIST += test-localeconv.c signature.h macros.h

## end   gnulib module localeconv-tests

## begin gnulib module localename

libtests_a_SOURCES += localename.c

EXTRA_DIST += localename.h

## end   gnulib module localename

## begin gnulib module localename-tests

GNULIB_TESTS += test-localename
check_PROGRAMS += test-localename
test_localename_LDADD = $(LDADD) @INTL_MACOSX_LIBS@ $(LIBTHREAD)

EXTRA_DIST += test-localename.c macros.h

## end   gnulib module localename-tests

## begin gnulib module lseek-tests

GNULIB_TESTS += test-lseek.sh
check_PROGRAMS += test-lseek
EXTRA_DIST += test-lseek.c test-lseek.sh signature.h macros.h

## end   gnulib module lseek-tests

## begin gnulib module lstat-tests

GNULIB_TESTS += test-lstat
check_PROGRAMS += test-lstat
EXTRA_DIST += test-lstat.h test-lstat.c signature.h macros.h

## end   gnulib module lstat-tests

## begin gnulib module malloca-tests

GNULIB_TESTS += test-malloca
check_PROGRAMS += test-malloca

EXTRA_DIST += test-malloca.c

## end   gnulib module malloca-tests

## begin gnulib module math

BUILT_SOURCES += math.h
libtests_a_SOURCES += math.c

# We need the following in order to create <math.h> when the system
# doesn't have one that works with the given compiler.
math.h: math.in.h $(top_builddir)/config.status $(CXXDEFS_H) $(ARG_NONNULL_H) $(WARN_ON_USE_H)
	$(AM_V_GEN)rm -f $@-t $@ && \
	{ echo '/* DO NOT EDIT! GENERATED AUTOMATICALLY! */' && \
	  sed -e 's|@''GUARD_PREFIX''@|GL|g' \
	      -e 's|@''INCLUDE_NEXT_AS_FIRST_DIRECTIVE''@|$(INCLUDE_NEXT_AS_FIRST_DIRECTIVE)|g' \
	      -e 's|@''PRAGMA_SYSTEM_HEADER''@|@PRAGMA_SYSTEM_HEADER@|g' \
	      -e 's|@''PRAGMA_COLUMNS''@|@PRAGMA_COLUMNS@|g' \
	      -e 's|@''NEXT_AS_FIRST_DIRECTIVE_MATH_H''@|$(NEXT_AS_FIRST_DIRECTIVE_MATH_H)|g' \
	      -e 's/@''GNULIB_ACOSF''@/$(GNULIB_ACOSF)/g' \
	      -e 's/@''GNULIB_ACOSL''@/$(GNULIB_ACOSL)/g' \
	      -e 's/@''GNULIB_ASINF''@/$(GNULIB_ASINF)/g' \
	      -e 's/@''GNULIB_ASINL''@/$(GNULIB_ASINL)/g' \
	      -e 's/@''GNULIB_ATANF''@/$(GNULIB_ATANF)/g' \
	      -e 's/@''GNULIB_ATANL''@/$(GNULIB_ATANL)/g' \
	      -e 's/@''GNULIB_ATAN2F''@/$(GNULIB_ATAN2F)/g' \
	      -e 's/@''GNULIB_CBRT''@/$(GNULIB_CBRT)/g' \
	      -e 's/@''GNULIB_CBRTF''@/$(GNULIB_CBRTF)/g' \
	      -e 's/@''GNULIB_CBRTL''@/$(GNULIB_CBRTL)/g' \
	      -e 's/@''GNULIB_CEIL''@/$(GNULIB_CEIL)/g' \
	      -e 's/@''GNULIB_CEILF''@/$(GNULIB_CEILF)/g' \
	      -e 's/@''GNULIB_CEILL''@/$(GNULIB_CEILL)/g' \
	      -e 's/@''GNULIB_COPYSIGN''@/$(GNULIB_COPYSIGN)/g' \
	      -e 's/@''GNULIB_COPYSIGNF''@/$(GNULIB_COPYSIGNF)/g' \
	      -e 's/@''GNULIB_COPYSIGNL''@/$(GNULIB_COPYSIGNL)/g' \
	      -e 's/@''GNULIB_COSF''@/$(GNULIB_COSF)/g' \
	      -e 's/@''GNULIB_COSL''@/$(GNULIB_COSL)/g' \
	      -e 's/@''GNULIB_COSHF''@/$(GNULIB_COSHF)/g' \
	      -e 's/@''GNULIB_EXPF''@/$(GNULIB_EXPF)/g' \
	      -e 's/@''GNULIB_EXPL''@/$(GNULIB_EXPL)/g' \
	      -e 's/@''GNULIB_EXP2''@/$(GNULIB_EXP2)/g' \
	      -e 's/@''GNULIB_EXP2F''@/$(GNULIB_EXP2F)/g' \
	      -e 's/@''GNULIB_EXP2L''@/$(GNULIB_EXP2L)/g' \
	      -e 's/@''GNULIB_EXPM1''@/$(GNULIB_EXPM1)/g' \
	      -e 's/@''GNULIB_EXPM1F''@/$(GNULIB_EXPM1F)/g' \
	      -e 's/@''GNULIB_EXPM1L''@/$(GNULIB_EXPM1L)/g' \
	      -e 's/@''GNULIB_FABSF''@/$(GNULIB_FABSF)/g' \
	      -e 's/@''GNULIB_FABSL''@/$(GNULIB_FABSL)/g' \
	      -e 's/@''GNULIB_FLOOR''@/$(GNULIB_FLOOR)/g' \
	      -e 's/@''GNULIB_FLOORF''@/$(GNULIB_FLOORF)/g' \
	      -e 's/@''GNULIB_FLOORL''@/$(GNULIB_FLOORL)/g' \
	      -e 's/@''GNULIB_FMA''@/$(GNULIB_FMA)/g' \
	      -e 's/@''GNULIB_FMAF''@/$(GNULIB_FMAF)/g' \
	      -e 's/@''GNULIB_FMAL''@/$(GNULIB_FMAL)/g' \
	      -e 's/@''GNULIB_FMOD''@/$(GNULIB_FMOD)/g' \
	      -e 's/@''GNULIB_FMODF''@/$(GNULIB_FMODF)/g' \
	      -e 's/@''GNULIB_FMODL''@/$(GNULIB_FMODL)/g' \
	      -e 's/@''GNULIB_FREXPF''@/$(GNULIB_FREXPF)/g' \
	      -e 's/@''GNULIB_FREXP''@/$(GNULIB_FREXP)/g' \
	      -e 's/@''GNULIB_FREXPL''@/$(GNULIB_FREXPL)/g' \
	      -e 's/@''GNULIB_HYPOT''@/$(GNULIB_HYPOT)/g' \
	      -e 's/@''GNULIB_HYPOTF''@/$(GNULIB_HYPOTF)/g' \
	      -e 's/@''GNULIB_HYPOTL''@/$(GNULIB_HYPOTL)/g' \
	      < $(srcdir)/math.in.h | \
	  sed -e 's/@''GNULIB_ILOGB''@/$(GNULIB_ILOGB)/g' \
	      -e 's/@''GNULIB_ILOGBF''@/$(GNULIB_ILOGBF)/g' \
	      -e 's/@''GNULIB_ILOGBL''@/$(GNULIB_ILOGBL)/g' \
	      -e 's/@''GNULIB_ISFINITE''@/$(GNULIB_ISFINITE)/g' \
	      -e 's/@''GNULIB_ISINF''@/$(GNULIB_ISINF)/g' \
	      -e 's/@''GNULIB_ISNAN''@/$(GNULIB_ISNAN)/g' \
	      -e 's/@''GNULIB_ISNANF''@/$(GNULIB_ISNANF)/g' \
	      -e 's/@''GNULIB_ISNAND''@/$(GNULIB_ISNAND)/g' \
	      -e 's/@''GNULIB_ISNANL''@/$(GNULIB_ISNANL)/g' \
	      -e 's/@''GNULIB_LDEXPF''@/$(GNULIB_LDEXPF)/g' \
	      -e 's/@''GNULIB_LDEXPL''@/$(GNULIB_LDEXPL)/g' \
	      -e 's/@''GNULIB_LOG''@/$(GNULIB_LOG)/g' \
	      -e 's/@''GNULIB_LOGF''@/$(GNULIB_LOGF)/g' \
	      -e 's/@''GNULIB_LOGL''@/$(GNULIB_LOGL)/g' \
	      -e 's/@''GNULIB_LOG10''@/$(GNULIB_LOG10)/g' \
	      -e 's/@''GNULIB_LOG10F''@/$(GNULIB_LOG10F)/g' \
	      -e 's/@''GNULIB_LOG10L''@/$(GNULIB_LOG10L)/g' \
	      -e 's/@''GNULIB_LOG1P''@/$(GNULIB_LOG1P)/g' \
	      -e 's/@''GNULIB_LOG1PF''@/$(GNULIB_LOG1PF)/g' \
	      -e 's/@''GNULIB_LOG1PL''@/$(GNULIB_LOG1PL)/g' \
	      -e 's/@''GNULIB_LOG2''@/$(GNULIB_LOG2)/g' \
	      -e 's/@''GNULIB_LOG2F''@/$(GNULIB_LOG2F)/g' \
	      -e 's/@''GNULIB_LOG2L''@/$(GNULIB_LOG2L)/g' \
	      -e 's/@''GNULIB_LOGB''@/$(GNULIB_LOGB)/g' \
	      -e 's/@''GNULIB_LOGBF''@/$(GNULIB_LOGBF)/g' \
	      -e 's/@''GNULIB_LOGBL''@/$(GNULIB_LOGBL)/g' \
	      -e 's/@''GNULIB_MODF''@/$(GNULIB_MODF)/g' \
	      -e 's/@''GNULIB_MODFF''@/$(GNULIB_MODFF)/g' \
	      -e 's/@''GNULIB_MODFL''@/$(GNULIB_MODFL)/g' \
	      -e 's/@''GNULIB_POWF''@/$(GNULIB_POWF)/g' \
	      -e 's/@''GNULIB_REMAINDER''@/$(GNULIB_REMAINDER)/g' \
	      -e 's/@''GNULIB_REMAINDERF''@/$(GNULIB_REMAINDERF)/g' \
	      -e 's/@''GNULIB_REMAINDERL''@/$(GNULIB_REMAINDERL)/g' \
	      -e 's/@''GNULIB_RINT''@/$(GNULIB_RINT)/g' \
	      -e 's/@''GNULIB_RINTF''@/$(GNULIB_RINTF)/g' \
	      -e 's/@''GNULIB_RINTL''@/$(GNULIB_RINTL)/g' \
	      -e 's/@''GNULIB_ROUND''@/$(GNULIB_ROUND)/g' \
	      -e 's/@''GNULIB_ROUNDF''@/$(GNULIB_ROUNDF)/g' \
	      -e 's/@''GNULIB_ROUNDL''@/$(GNULIB_ROUNDL)/g' \
	      -e 's/@''GNULIB_SIGNBIT''@/$(GNULIB_SIGNBIT)/g' \
	      -e 's/@''GNULIB_SINF''@/$(GNULIB_SINF)/g' \
	      -e 's/@''GNULIB_SINL''@/$(GNULIB_SINL)/g' \
	      -e 's/@''GNULIB_SINHF''@/$(GNULIB_SINHF)/g' \
	      -e 's/@''GNULIB_SQRTF''@/$(GNULIB_SQRTF)/g' \
	      -e 's/@''GNULIB_SQRTL''@/$(GNULIB_SQRTL)/g' \
	      -e 's/@''GNULIB_TANF''@/$(GNULIB_TANF)/g' \
	      -e 's/@''GNULIB_TANL''@/$(GNULIB_TANL)/g' \
	      -e 's/@''GNULIB_TANHF''@/$(GNULIB_TANHF)/g' \
	      -e 's/@''GNULIB_TRUNC''@/$(GNULIB_TRUNC)/g' \
	      -e 's/@''GNULIB_TRUNCF''@/$(GNULIB_TRUNCF)/g' \
	      -e 's/@''GNULIB_TRUNCL''@/$(GNULIB_TRUNCL)/g' \
	  | \
	  sed -e 's|@''HAVE_ACOSF''@|$(HAVE_ACOSF)|g' \
	      -e 's|@''HAVE_ACOSL''@|$(HAVE_ACOSL)|g' \
	      -e 's|@''HAVE_ASINF''@|$(HAVE_ASINF)|g' \
	      -e 's|@''HAVE_ASINL''@|$(HAVE_ASINL)|g' \
	      -e 's|@''HAVE_ATANF''@|$(HAVE_ATANF)|g' \
	      -e 's|@''HAVE_ATANL''@|$(HAVE_ATANL)|g' \
	      -e 's|@''HAVE_ATAN2F''@|$(HAVE_ATAN2F)|g' \
	      -e 's|@''HAVE_CBRT''@|$(HAVE_CBRT)|g' \
	      -e 's|@''HAVE_CBRTF''@|$(HAVE_CBRTF)|g' \
	      -e 's|@''HAVE_CBRTL''@|$(HAVE_CBRTL)|g' \
	      -e 's|@''HAVE_COPYSIGN''@|$(HAVE_COPYSIGN)|g' \
	      -e 's|@''HAVE_COPYSIGNL''@|$(HAVE_COPYSIGNL)|g' \
	      -e 's|@''HAVE_COSF''@|$(HAVE_COSF)|g' \
	      -e 's|@''HAVE_COSL''@|$(HAVE_COSL)|g' \
	      -e 's|@''HAVE_COSHF''@|$(HAVE_COSHF)|g' \
	      -e 's|@''HAVE_EXPF''@|$(HAVE_EXPF)|g' \
	      -e 's|@''HAVE_EXPL''@|$(HAVE_EXPL)|g' \
	      -e 's|@''HAVE_EXPM1''@|$(HAVE_EXPM1)|g' \
	      -e 's|@''HAVE_EXPM1F''@|$(HAVE_EXPM1F)|g' \
	      -e 's|@''HAVE_FABSF''@|$(HAVE_FABSF)|g' \
	      -e 's|@''HAVE_FABSL''@|$(HAVE_FABSL)|g' \
	      -e 's|@''HAVE_FMA''@|$(HAVE_FMA)|g' \
	      -e 's|@''HAVE_FMAF''@|$(HAVE_FMAF)|g' \
	      -e 's|@''HAVE_FMAL''@|$(HAVE_FMAL)|g' \
	      -e 's|@''HAVE_FMODF''@|$(HAVE_FMODF)|g' \
	      -e 's|@''HAVE_FMODL''@|$(HAVE_FMODL)|g' \
	      -e 's|@''HAVE_FREXPF''@|$(HAVE_FREXPF)|g' \
	      -e 's|@''HAVE_HYPOTF''@|$(HAVE_HYPOTF)|g' \
	      -e 's|@''HAVE_HYPOTL''@|$(HAVE_HYPOTL)|g' \
	      -e 's|@''HAVE_ILOGB''@|$(HAVE_ILOGB)|g' \
	      -e 's|@''HAVE_ILOGBF''@|$(HAVE_ILOGBF)|g' \
	      -e 's|@''HAVE_ILOGBL''@|$(HAVE_ILOGBL)|g' \
	      -e 's|@''HAVE_ISNANF''@|$(HAVE_ISNANF)|g' \
	      -e 's|@''HAVE_ISNAND''@|$(HAVE_ISNAND)|g' \
	      -e 's|@''HAVE_ISNANL''@|$(HAVE_ISNANL)|g' \
	      -e 's|@''HAVE_LDEXPF''@|$(HAVE_LDEXPF)|g' \
	      -e 's|@''HAVE_LOGF''@|$(HAVE_LOGF)|g' \
	      -e 's|@''HAVE_LOGL''@|$(HAVE_LOGL)|g' \
	      -e 's|@''HAVE_LOG10F''@|$(HAVE_LOG10F)|g' \
	      -e 's|@''HAVE_LOG10L''@|$(HAVE_LOG10L)|g' \
	      -e 's|@''HAVE_LOG1P''@|$(HAVE_LOG1P)|g' \
	      -e 's|@''HAVE_LOG1PF''@|$(HAVE_LOG1PF)|g' \
	      -e 's|@''HAVE_LOG1PL''@|$(HAVE_LOG1PL)|g' \
	      -e 's|@''HAVE_LOGBF''@|$(HAVE_LOGBF)|g' \
	      -e 's|@''HAVE_LOGBL''@|$(HAVE_LOGBL)|g' \
	      -e 's|@''HAVE_MODFF''@|$(HAVE_MODFF)|g' \
	      -e 's|@''HAVE_MODFL''@|$(HAVE_MODFL)|g' \
	      -e 's|@''HAVE_POWF''@|$(HAVE_POWF)|g' \
	      -e 's|@''HAVE_REMAINDER''@|$(HAVE_REMAINDER)|g' \
	      -e 's|@''HAVE_REMAINDERF''@|$(HAVE_REMAINDERF)|g' \
	      -e 's|@''HAVE_RINT''@|$(HAVE_RINT)|g' \
	      -e 's|@''HAVE_RINTL''@|$(HAVE_RINTL)|g' \
	      -e 's|@''HAVE_SINF''@|$(HAVE_SINF)|g' \
	      -e 's|@''HAVE_SINL''@|$(HAVE_SINL)|g' \
	      -e 's|@''HAVE_SINHF''@|$(HAVE_SINHF)|g' \
	      -e 's|@''HAVE_SQRTF''@|$(HAVE_SQRTF)|g' \
	      -e 's|@''HAVE_SQRTL''@|$(HAVE_SQRTL)|g' \
	      -e 's|@''HAVE_TANF''@|$(HAVE_TANF)|g' \
	      -e 's|@''HAVE_TANL''@|$(HAVE_TANL)|g' \
	      -e 's|@''HAVE_TANHF''@|$(HAVE_TANHF)|g' \
	      -e 's|@''HAVE_DECL_ACOSL''@|$(HAVE_DECL_ACOSL)|g' \
	      -e 's|@''HAVE_DECL_ASINL''@|$(HAVE_DECL_ASINL)|g' \
	      -e 's|@''HAVE_DECL_ATANL''@|$(HAVE_DECL_ATANL)|g' \
	      -e 's|@''HAVE_DECL_CBRTF''@|$(HAVE_DECL_CBRTF)|g' \
	      -e 's|@''HAVE_DECL_CBRTL''@|$(HAVE_DECL_CBRTL)|g' \
	      -e 's|@''HAVE_DECL_CEILF''@|$(HAVE_DECL_CEILF)|g' \
	      -e 's|@''HAVE_DECL_CEILL''@|$(HAVE_DECL_CEILL)|g' \
	      -e 's|@''HAVE_DECL_COPYSIGNF''@|$(HAVE_DECL_COPYSIGNF)|g' \
	      -e 's|@''HAVE_DECL_COSL''@|$(HAVE_DECL_COSL)|g' \
	      -e 's|@''HAVE_DECL_EXPL''@|$(HAVE_DECL_EXPL)|g' \
	      -e 's|@''HAVE_DECL_EXP2''@|$(HAVE_DECL_EXP2)|g' \
	      -e 's|@''HAVE_DECL_EXP2F''@|$(HAVE_DECL_EXP2F)|g' \
	      -e 's|@''HAVE_DECL_EXP2L''@|$(HAVE_DECL_EXP2L)|g' \
	      -e 's|@''HAVE_DECL_EXPM1L''@|$(HAVE_DECL_EXPM1L)|g' \
	      -e 's|@''HAVE_DECL_FLOORF''@|$(HAVE_DECL_FLOORF)|g' \
	      -e 's|@''HAVE_DECL_FLOORL''@|$(HAVE_DECL_FLOORL)|g' \
	      -e 's|@''HAVE_DECL_FREXPL''@|$(HAVE_DECL_FREXPL)|g' \
	      -e 's|@''HAVE_DECL_LDEXPL''@|$(HAVE_DECL_LDEXPL)|g' \
	      -e 's|@''HAVE_DECL_LOGL''@|$(HAVE_DECL_LOGL)|g' \
	      -e 's|@''HAVE_DECL_LOG10L''@|$(HAVE_DECL_LOG10L)|g' \
	      -e 's|@''HAVE_DECL_LOG2''@|$(HAVE_DECL_LOG2)|g' \
	      -e 's|@''HAVE_DECL_LOG2F''@|$(HAVE_DECL_LOG2F)|g' \
	      -e 's|@''HAVE_DECL_LOG2L''@|$(HAVE_DECL_LOG2L)|g' \
	      -e 's|@''HAVE_DECL_LOGB''@|$(HAVE_DECL_LOGB)|g' \
	      -e 's|@''HAVE_DECL_REMAINDER''@|$(HAVE_DECL_REMAINDER)|g' \
	      -e 's|@''HAVE_DECL_REMAINDERL''@|$(HAVE_DECL_REMAINDERL)|g' \
	      -e 's|@''HAVE_DECL_RINTF''@|$(HAVE_DECL_RINTF)|g' \
	      -e 's|@''HAVE_DECL_ROUND''@|$(HAVE_DECL_ROUND)|g' \
	      -e 's|@''HAVE_DECL_ROUNDF''@|$(HAVE_DECL_ROUNDF)|g' \
	      -e 's|@''HAVE_DECL_ROUNDL''@|$(HAVE_DECL_ROUNDL)|g' \
	      -e 's|@''HAVE_DECL_SINL''@|$(HAVE_DECL_SINL)|g' \
	      -e 's|@''HAVE_DECL_SQRTL''@|$(HAVE_DECL_SQRTL)|g' \
	      -e 's|@''HAVE_DECL_TANL''@|$(HAVE_DECL_TANL)|g' \
	      -e 's|@''HAVE_DECL_TRUNC''@|$(HAVE_DECL_TRUNC)|g' \
	      -e 's|@''HAVE_DECL_TRUNCF''@|$(HAVE_DECL_TRUNCF)|g' \
	      -e 's|@''HAVE_DECL_TRUNCL''@|$(HAVE_DECL_TRUNCL)|g' \
	  | \
	  sed -e 's|@''REPLACE_ACOSF''@|$(REPLACE_ACOSF)|g' \
	      -e 's|@''REPLACE_ASINF''@|$(REPLACE_ASINF)|g' \
	      -e 's|@''REPLACE_ATANF''@|$(REPLACE_ATANF)|g' \
	      -e 's|@''REPLACE_ATAN2F''@|$(REPLACE_ATAN2F)|g' \
	      -e 's|@''REPLACE_CBRTF''@|$(REPLACE_CBRTF)|g' \
	      -e 's|@''REPLACE_CBRTL''@|$(REPLACE_CBRTL)|g' \
	      -e 's|@''REPLACE_CEIL''@|$(REPLACE_CEIL)|g' \
	      -e 's|@''REPLACE_CEILF''@|$(REPLACE_CEILF)|g' \
	      -e 's|@''REPLACE_CEILL''@|$(REPLACE_CEILL)|g' \
	      -e 's|@''REPLACE_COSF''@|$(REPLACE_COSF)|g' \
	      -e 's|@''REPLACE_COSHF''@|$(REPLACE_COSHF)|g' \
	      -e 's|@''REPLACE_EXPF''@|$(REPLACE_EXPF)|g' \
	      -e 's|@''REPLACE_EXPM1''@|$(REPLACE_EXPM1)|g' \
	      -e 's|@''REPLACE_EXPM1F''@|$(REPLACE_EXPM1F)|g' \
	      -e 's|@''REPLACE_EXP2''@|$(REPLACE_EXP2)|g' \
	      -e 's|@''REPLACE_EXP2L''@|$(REPLACE_EXP2L)|g' \
	      -e 's|@''REPLACE_FABSL''@|$(REPLACE_FABSL)|g' \
	      -e 's|@''REPLACE_FLOOR''@|$(REPLACE_FLOOR)|g' \
	      -e 's|@''REPLACE_FLOORF''@|$(REPLACE_FLOORF)|g' \
	      -e 's|@''REPLACE_FLOORL''@|$(REPLACE_FLOORL)|g' \
	      -e 's|@''REPLACE_FMA''@|$(REPLACE_FMA)|g' \
	      -e 's|@''REPLACE_FMAF''@|$(REPLACE_FMAF)|g' \
	      -e 's|@''REPLACE_FMAL''@|$(REPLACE_FMAL)|g' \
	      -e 's|@''REPLACE_FMOD''@|$(REPLACE_FMOD)|g' \
	      -e 's|@''REPLACE_FMODF''@|$(REPLACE_FMODF)|g' \
	      -e 's|@''REPLACE_FMODL''@|$(REPLACE_FMODL)|g' \
	      -e 's|@''REPLACE_FREXPF''@|$(REPLACE_FREXPF)|g' \
	      -e 's|@''REPLACE_FREXP''@|$(REPLACE_FREXP)|g' \
	      -e 's|@''REPLACE_FREXPL''@|$(REPLACE_FREXPL)|g' \
	      -e 's|@''REPLACE_HUGE_VAL''@|$(REPLACE_HUGE_VAL)|g' \
	      -e 's|@''REPLACE_HYPOT''@|$(REPLACE_HYPOT)|g' \
	      -e 's|@''REPLACE_HYPOTF''@|$(REPLACE_HYPOTF)|g' \
	      -e 's|@''REPLACE_HYPOTL''@|$(REPLACE_HYPOTL)|g' \
	      -e 's|@''REPLACE_ILOGB''@|$(REPLACE_ILOGB)|g' \
	      -e 's|@''REPLACE_ILOGBF''@|$(REPLACE_ILOGBF)|g' \
	      -e 's|@''REPLACE_ILOGBL''@|$(REPLACE_ILOGBL)|g' \
	      -e 's|@''REPLACE_ISFINITE''@|$(REPLACE_ISFINITE)|g' \
	      -e 's|@''REPLACE_ISINF''@|$(REPLACE_ISINF)|g' \
	      -e 's|@''REPLACE_ISNAN''@|$(REPLACE_ISNAN)|g' \
	      -e 's|@''REPLACE_ITOLD''@|$(REPLACE_ITOLD)|g' \
	      -e 's|@''REPLACE_LDEXPL''@|$(REPLACE_LDEXPL)|g' \
	      -e 's|@''REPLACE_LOG''@|$(REPLACE_LOG)|g' \
	      -e 's|@''REPLACE_LOGF''@|$(REPLACE_LOGF)|g' \
	      -e 's|@''REPLACE_LOGL''@|$(REPLACE_LOGL)|g' \
	      -e 's|@''REPLACE_LOG10''@|$(REPLACE_LOG10)|g' \
	      -e 's|@''REPLACE_LOG10F''@|$(REPLACE_LOG10F)|g' \
	      -e 's|@''REPLACE_LOG10L''@|$(REPLACE_LOG10L)|g' \
	      -e 's|@''REPLACE_LOG1P''@|$(REPLACE_LOG1P)|g' \
	      -e 's|@''REPLACE_LOG1PF''@|$(REPLACE_LOG1PF)|g' \
	      -e 's|@''REPLACE_LOG1PL''@|$(REPLACE_LOG1PL)|g' \
	      -e 's|@''REPLACE_LOG2''@|$(REPLACE_LOG2)|g' \
	      -e 's|@''REPLACE_LOG2F''@|$(REPLACE_LOG2F)|g' \
	      -e 's|@''REPLACE_LOG2L''@|$(REPLACE_LOG2L)|g' \
	      -e 's|@''REPLACE_LOGB''@|$(REPLACE_LOGB)|g' \
	      -e 's|@''REPLACE_LOGBF''@|$(REPLACE_LOGBF)|g' \
	      -e 's|@''REPLACE_LOGBL''@|$(REPLACE_LOGBL)|g' \
	      -e 's|@''REPLACE_MODF''@|$(REPLACE_MODF)|g' \
	      -e 's|@''REPLACE_MODFF''@|$(REPLACE_MODFF)|g' \
	      -e 's|@''REPLACE_MODFL''@|$(REPLACE_MODFL)|g' \
	      -e 's|@''REPLACE_NAN''@|$(REPLACE_NAN)|g' \
	      -e 's|@''REPLACE_REMAINDER''@|$(REPLACE_REMAINDER)|g' \
	      -e 's|@''REPLACE_REMAINDERF''@|$(REPLACE_REMAINDERF)|g' \
	      -e 's|@''REPLACE_REMAINDERL''@|$(REPLACE_REMAINDERL)|g' \
	      -e 's|@''REPLACE_ROUND''@|$(REPLACE_ROUND)|g' \
	      -e 's|@''REPLACE_ROUNDF''@|$(REPLACE_ROUNDF)|g' \
	      -e 's|@''REPLACE_ROUNDL''@|$(REPLACE_ROUNDL)|g' \
	      -e 's|@''REPLACE_SIGNBIT''@|$(REPLACE_SIGNBIT)|g' \
	      -e 's|@''REPLACE_SIGNBIT_USING_GCC''@|$(REPLACE_SIGNBIT_USING_GCC)|g' \
	      -e 's|@''REPLACE_SINF''@|$(REPLACE_SINF)|g' \
	      -e 's|@''REPLACE_SINHF''@|$(REPLACE_SINHF)|g' \
	      -e 's|@''REPLACE_SQRTF''@|$(REPLACE_SQRTF)|g' \
	      -e 's|@''REPLACE_SQRTL''@|$(REPLACE_SQRTL)|g' \
	      -e 's|@''REPLACE_TANF''@|$(REPLACE_TANF)|g' \
	      -e 's|@''REPLACE_TANHF''@|$(REPLACE_TANHF)|g' \
	      -e 's|@''REPLACE_TRUNC''@|$(REPLACE_TRUNC)|g' \
	      -e 's|@''REPLACE_TRUNCF''@|$(REPLACE_TRUNCF)|g' \
	      -e 's|@''REPLACE_TRUNCL''@|$(REPLACE_TRUNCL)|g' \
	      -e '/definitions of _GL_FUNCDECL_RPL/r $(CXXDEFS_H)' \
	      -e '/definition of _GL_ARG_NONNULL/r $(ARG_NONNULL_H)' \
	      -e '/definition of _GL_WARN_ON_USE/r $(WARN_ON_USE_H)'; \
	} > $@-t && \
	mv $@-t $@
MOSTLYCLEANFILES += math.h math.h-t

EXTRA_DIST += math.in.h

## end   gnulib module math

## begin gnulib module math-tests

GNULIB_TESTS += test-math
check_PROGRAMS += test-math
EXTRA_DIST += test-math.c macros.h

## end   gnulib module math-tests

## begin gnulib module mbrtowc-tests

GNULIB_TESTS += \
  test-mbrtowc1.sh test-mbrtowc2.sh test-mbrtowc3.sh test-mbrtowc4.sh \
  test-mbrtowc5.sh \
  test-mbrtowc-w32-1.sh test-mbrtowc-w32-2.sh test-mbrtowc-w32-3.sh \
  test-mbrtowc-w32-4.sh test-mbrtowc-w32-5.sh
TESTS_ENVIRONMENT += \
  LOCALE_FR='@LOCALE_FR@' \
  LOCALE_FR_UTF8='@LOCALE_FR_UTF8@' \
  LOCALE_JA='@LOCALE_JA@' \
  LOCALE_ZH_CN='@LOCALE_ZH_CN@'
check_PROGRAMS += test-mbrtowc test-mbrtowc-w32
EXTRA_DIST += test-mbrtowc1.sh test-mbrtowc2.sh test-mbrtowc3.sh test-mbrtowc4.sh test-mbrtowc5.sh test-mbrtowc.c test-mbrtowc-w32-1.sh test-mbrtowc-w32-2.sh test-mbrtowc-w32-3.sh test-mbrtowc-w32-4.sh test-mbrtowc-w32-5.sh test-mbrtowc-w32.c signature.h macros.h

## end   gnulib module mbrtowc-tests

## begin gnulib module mbsinit-tests

GNULIB_TESTS += test-mbsinit.sh
TESTS_ENVIRONMENT += LOCALE_FR_UTF8='@LOCALE_FR_UTF8@'
check_PROGRAMS += test-mbsinit

EXTRA_DIST += test-mbsinit.sh test-mbsinit.c signature.h macros.h

## end   gnulib module mbsinit-tests

## begin gnulib module mbsrtowcs-tests

GNULIB_TESTS += test-mbsrtowcs1.sh test-mbsrtowcs2.sh test-mbsrtowcs3.sh test-mbsrtowcs4.sh
TESTS_ENVIRONMENT += \
  LOCALE_FR='@LOCALE_FR@' \
  LOCALE_FR_UTF8='@LOCALE_FR_UTF8@' \
  LOCALE_JA='@LOCALE_JA@' \
  LOCALE_ZH_CN='@LOCALE_ZH_CN@'
check_PROGRAMS += test-mbsrtowcs

EXTRA_DIST += test-mbsrtowcs1.sh test-mbsrtowcs2.sh test-mbsrtowcs3.sh test-mbsrtowcs4.sh test-mbsrtowcs.c signature.h macros.h

## end   gnulib module mbsrtowcs-tests

## begin gnulib module memchr-tests

GNULIB_TESTS += test-memchr
check_PROGRAMS += test-memchr
EXTRA_DIST += test-memchr.c zerosize-ptr.h signature.h macros.h

## end   gnulib module memchr-tests

## begin gnulib module nanosleep


EXTRA_DIST += nanosleep.c

EXTRA_libtests_a_SOURCES += nanosleep.c

## end   gnulib module nanosleep

## begin gnulib module nanosleep-tests

GNULIB_TESTS += test-nanosleep
check_PROGRAMS += test-nanosleep
test_nanosleep_LDADD = $(LDADD) $(LIB_NANOSLEEP)
EXTRA_DIST += test-nanosleep.c signature.h macros.h

## end   gnulib module nanosleep-tests

## begin gnulib module net_if-tests

GNULIB_TESTS += test-net_if
check_PROGRAMS += test-net_if
test_net_if_LDADD = $(LDADD) @NET_IF_LIB@
EXTRA_DIST += test-net_if.c signature.h

## end   gnulib module net_if-tests

## begin gnulib module netdb-tests

GNULIB_TESTS += test-netdb
check_PROGRAMS += test-netdb
EXTRA_DIST += test-netdb.c

## end   gnulib module netdb-tests

## begin gnulib module netinet_in-tests

GNULIB_TESTS += test-netinet_in
check_PROGRAMS += test-netinet_in
EXTRA_DIST += test-netinet_in.c

## end   gnulib module netinet_in-tests

## begin gnulib module nl_langinfo-tests

GNULIB_TESTS += test-nl_langinfo.sh
TESTS_ENVIRONMENT += LOCALE_FR='@LOCALE_FR@' LOCALE_FR_UTF8='@LOCALE_FR_UTF8@'
check_PROGRAMS += test-nl_langinfo
EXTRA_DIST += test-nl_langinfo.sh test-nl_langinfo.c signature.h macros.h

## end   gnulib module nl_langinfo-tests

## begin gnulib module nonblocking-pipe-tests

GNULIB_TESTS += test-nonblocking-pipe.sh
check_PROGRAMS += test-nonblocking-pipe-main test-nonblocking-pipe-child
test_nonblocking_pipe_main_LDADD = $(LDADD) @LIBINTL@
EXTRA_DIST += test-nonblocking-pipe.sh test-nonblocking-pipe-main.c test-nonblocking-pipe-child.c test-nonblocking-pipe.h test-nonblocking-writer.h test-nonblocking-reader.h test-nonblocking-misc.h macros.h

## end   gnulib module nonblocking-pipe-tests

## begin gnulib module nonblocking-socket-tests

GNULIB_TESTS += test-nonblocking-socket.sh
check_PROGRAMS += test-nonblocking-socket-main test-nonblocking-socket-child
test_nonblocking_socket_main_LDADD = $(LDADD) $(LIBSOCKET) @LIBINTL@
test_nonblocking_socket_child_LDADD = $(LDADD) $(LIBSOCKET)
EXTRA_DIST += test-nonblocking-socket.sh test-nonblocking-socket-main.c test-nonblocking-socket-child.c test-nonblocking-socket.h test-nonblocking-writer.h test-nonblocking-reader.h test-nonblocking-misc.h socket-server.h socket-client.h macros.h

## end   gnulib module nonblocking-socket-tests

## begin gnulib module nonblocking-tests

GNULIB_TESTS += test-nonblocking
check_PROGRAMS += test-nonblocking
test_nonblocking_LDADD = $(LDADD) $(LIBSOCKET)
EXTRA_DIST += test-nonblocking.c macros.h

## end   gnulib module nonblocking-tests

## begin gnulib module open-tests

GNULIB_TESTS += test-open
check_PROGRAMS += test-open
EXTRA_DIST += test-open.h test-open.c signature.h macros.h

## end   gnulib module open-tests

## begin gnulib module openpty-tests

GNULIB_TESTS += test-openpty
check_PROGRAMS += test-openpty
test_openpty_LDADD = $(LDADD) @PTY_LIB@
EXTRA_DIST += test-openpty.c signature.h

## end   gnulib module openpty-tests

## begin gnulib module passfd-tests

GNULIB_TESTS += test-passfd
check_PROGRAMS += test-passfd
test_passfd_LDADD = $(LDADD) @LIBSOCKET@
EXTRA_DIST += test-passfd.c macros.h

## end   gnulib module passfd-tests

## begin gnulib module pathmax-tests

GNULIB_TESTS += test-pathmax
check_PROGRAMS += test-pathmax
EXTRA_DIST += test-pathmax.c

## end   gnulib module pathmax-tests

## begin gnulib module perror-tests

GNULIB_TESTS += test-perror.sh test-perror2
check_PROGRAMS += test-perror test-perror2
EXTRA_DIST += macros.h signature.h test-perror.c test-perror2.c test-perror.sh

## end   gnulib module perror-tests

## begin gnulib module pipe-posix-tests

GNULIB_TESTS += test-pipe
check_PROGRAMS += test-pipe
EXTRA_DIST += test-pipe.c signature.h macros.h

## end   gnulib module pipe-posix-tests

## begin gnulib module pipe2-tests

GNULIB_TESTS += test-pipe2
check_PROGRAMS += test-pipe2
test_pipe2_LDADD = $(LDADD) $(LIBSOCKET)
EXTRA_DIST += test-pipe2.c signature.h macros.h

## end   gnulib module pipe2-tests

## begin gnulib module poll-h-tests

GNULIB_TESTS += test-poll-h
check_PROGRAMS += test-poll-h
EXTRA_DIST += test-poll-h.c

## end   gnulib module poll-h-tests

## begin gnulib module poll-tests

GNULIB_TESTS += test-poll
check_PROGRAMS += test-poll
test_poll_LDADD = $(LDADD) $(LIB_POLL) @LIBSOCKET@ $(INET_PTON_LIB)
EXTRA_DIST += test-poll.c signature.h macros.h

## end   gnulib module poll-tests

## begin gnulib module posix_openpt-tests

GNULIB_TESTS += test-posix_openpt
check_PROGRAMS += test-posix_openpt
EXTRA_DIST += test-posix_openpt.c signature.h macros.h

## end   gnulib module posix_openpt-tests

## begin gnulib module posix_spawn-internal


EXTRA_DIST += spawn_int.h spawni.c

EXTRA_libtests_a_SOURCES += spawni.c

## end   gnulib module posix_spawn-internal

## begin gnulib module posix_spawn_file_actions_addclose


EXTRA_DIST += spawn_faction_addclose.c spawn_int.h

EXTRA_libtests_a_SOURCES += spawn_faction_addclose.c

## end   gnulib module posix_spawn_file_actions_addclose

## begin gnulib module posix_spawn_file_actions_addclose-tests

GNULIB_TESTS += test-posix_spawn_file_actions_addclose
check_PROGRAMS += test-posix_spawn_file_actions_addclose
EXTRA_DIST += test-posix_spawn_file_actions_addclose.c signature.h macros.h

## end   gnulib module posix_spawn_file_actions_addclose-tests

## begin gnulib module posix_spawn_file_actions_adddup2


EXTRA_DIST += spawn_faction_adddup2.c spawn_int.h

EXTRA_libtests_a_SOURCES += spawn_faction_adddup2.c

## end   gnulib module posix_spawn_file_actions_adddup2

## begin gnulib module posix_spawn_file_actions_adddup2-tests

GNULIB_TESTS += test-posix_spawn_file_actions_adddup2
check_PROGRAMS += test-posix_spawn_file_actions_adddup2
EXTRA_DIST += test-posix_spawn_file_actions_adddup2.c signature.h macros.h

## end   gnulib module posix_spawn_file_actions_adddup2-tests

## begin gnulib module posix_spawn_file_actions_addopen


EXTRA_DIST += spawn_faction_addopen.c spawn_int.h

EXTRA_libtests_a_SOURCES += spawn_faction_addopen.c

## end   gnulib module posix_spawn_file_actions_addopen

## begin gnulib module posix_spawn_file_actions_addopen-tests

GNULIB_TESTS += test-posix_spawn_file_actions_addopen
check_PROGRAMS += test-posix_spawn_file_actions_addopen
EXTRA_DIST += test-posix_spawn_file_actions_addopen.c signature.h macros.h

## end   gnulib module posix_spawn_file_actions_addopen-tests

## begin gnulib module posix_spawn_file_actions_destroy


EXTRA_DIST += spawn_faction_destroy.c

EXTRA_libtests_a_SOURCES += spawn_faction_destroy.c

## end   gnulib module posix_spawn_file_actions_destroy

## begin gnulib module posix_spawn_file_actions_init


EXTRA_DIST += spawn_faction_init.c spawn_int.h

EXTRA_libtests_a_SOURCES += spawn_faction_init.c

## end   gnulib module posix_spawn_file_actions_init

## begin gnulib module posix_spawnattr_destroy


EXTRA_DIST += spawnattr_destroy.c

EXTRA_libtests_a_SOURCES += spawnattr_destroy.c

## end   gnulib module posix_spawnattr_destroy

## begin gnulib module posix_spawnattr_init


EXTRA_DIST += spawnattr_init.c

EXTRA_libtests_a_SOURCES += spawnattr_init.c

## end   gnulib module posix_spawnattr_init

## begin gnulib module posix_spawnattr_setflags


EXTRA_DIST += spawnattr_setflags.c

EXTRA_libtests_a_SOURCES += spawnattr_setflags.c

## end   gnulib module posix_spawnattr_setflags

## begin gnulib module posix_spawnattr_setsigmask


EXTRA_DIST += spawnattr_setsigmask.c

EXTRA_libtests_a_SOURCES += spawnattr_setsigmask.c

## end   gnulib module posix_spawnattr_setsigmask

## begin gnulib module posix_spawnp


EXTRA_DIST += spawnp.c

EXTRA_libtests_a_SOURCES += spawnp.c

## end   gnulib module posix_spawnp

## begin gnulib module posix_spawnp-tests

if POSIX_SPAWN_PORTED
GNULIB_TESTS += test-posix_spawn1 test-posix_spawn2
check_PROGRAMS += test-posix_spawn1 test-posix_spawn2

BUILT_SOURCES += test-posix_spawn1.sh
test-posix_spawn1.sh: test-posix_spawn1.in.sh
	$(AM_V_GEN)rm -f $@-t $@ && \
	cp $(srcdir)/test-posix_spawn1.in.sh $@-t && \
	mv $@-t $@
MOSTLYCLEANFILES += test-posix_spawn1.sh test-posix_spawn1.sh-t

BUILT_SOURCES += test-posix_spawn2.sh
test-posix_spawn2.sh: test-posix_spawn2.in.sh
	$(AM_V_GEN)rm -f $@-t $@ && \
	cp $(srcdir)/test-posix_spawn2.in.sh $@-t && \
	mv $@-t $@
MOSTLYCLEANFILES += test-posix_spawn2.sh test-posix_spawn2.sh-t
endif
EXTRA_DIST += test-posix_spawn1.c test-posix_spawn1.in.sh test-posix_spawn2.c test-posix_spawn2.in.sh signature.h

## end   gnulib module posix_spawnp-tests

## begin gnulib module pthread_sigmask-tests

GNULIB_TESTS += test-pthread_sigmask1 test-pthread_sigmask2
check_PROGRAMS += test-pthread_sigmask1 test-pthread_sigmask2
test_pthread_sigmask1_LDADD = $(LDADD) @LIB_PTHREAD_SIGMASK@
test_pthread_sigmask2_LDADD = $(LDADD) @LIB_PTHREAD_SIGMASK@ @LIBMULTITHREAD@
EXTRA_DIST += test-pthread_sigmask1.c test-pthread_sigmask2.c signature.h macros.h

## end   gnulib module pthread_sigmask-tests

## begin gnulib module ptsname


EXTRA_DIST += ptsname.c

EXTRA_libtests_a_SOURCES += ptsname.c

## end   gnulib module ptsname

## begin gnulib module ptsname-tests

GNULIB_TESTS += test-ptsname
check_PROGRAMS += test-ptsname
EXTRA_DIST += test-ptsname.c signature.h macros.h

## end   gnulib module ptsname-tests

## begin gnulib module ptsname_r


EXTRA_DIST += ptsname_r.c

EXTRA_libtests_a_SOURCES += ptsname_r.c

## end   gnulib module ptsname_r

## begin gnulib module ptsname_r-tests

GNULIB_TESTS += test-ptsname_r
check_PROGRAMS += test-ptsname_r
EXTRA_DIST += test-ptsname_r.c signature.h null-ptr.h macros.h

## end   gnulib module ptsname_r-tests

## begin gnulib module putenv


EXTRA_DIST += putenv.c

EXTRA_libtests_a_SOURCES += putenv.c

## end   gnulib module putenv

## begin gnulib module raise-tests

GNULIB_TESTS += test-raise
check_PROGRAMS += test-raise
EXTRA_DIST += test-raise.c signature.h macros.h

## end   gnulib module raise-tests

## begin gnulib module rawmemchr-tests

GNULIB_TESTS += test-rawmemchr
check_PROGRAMS += test-rawmemchr
EXTRA_DIST += test-rawmemchr.c zerosize-ptr.h signature.h macros.h

## end   gnulib module rawmemchr-tests

## begin gnulib module read


EXTRA_DIST += read.c

EXTRA_libtests_a_SOURCES += read.c

## end   gnulib module read

## begin gnulib module read-tests

GNULIB_TESTS += test-read
check_PROGRAMS += test-read
EXTRA_DIST += test-read.c signature.h macros.h

## end   gnulib module read-tests

## begin gnulib module readlink-tests

GNULIB_TESTS += test-readlink
check_PROGRAMS += test-readlink
EXTRA_DIST += test-readlink.h test-readlink.c signature.h macros.h

## end   gnulib module readlink-tests

## begin gnulib module recv-tests

GNULIB_TESTS += test-recv
check_PROGRAMS += test-recv
test_recv_LDADD = $(LDADD) @LIBSOCKET@
EXTRA_DIST += test-recv.c signature.h macros.h

## end   gnulib module recv-tests

## begin gnulib module regex-tests

GNULIB_TESTS += test-regex
check_PROGRAMS += test-regex
test_regex_LDADD = $(LDADD) @LIBINTL@ $(LIBTHREAD) $(LIB_PTHREAD)
EXTRA_DIST += test-regex.c macros.h

## end   gnulib module regex-tests

## begin gnulib module same-inode


EXTRA_DIST += same-inode.h

## end   gnulib module same-inode

## begin gnulib module sched-tests

GNULIB_TESTS += test-sched
check_PROGRAMS += test-sched
EXTRA_DIST += test-sched.c

## end   gnulib module sched-tests

## begin gnulib module select-tests

GNULIB_TESTS += test-select test-select-in.sh test-select-out.sh
# test-select-stdin has to be run by hand.
check_PROGRAMS += test-select test-select-fd test-select-stdin
test_select_LDADD = $(LDADD) @LIB_SELECT@ @LIBSOCKET@ $(INET_PTON_LIB)
test_select_fd_LDADD = $(LDADD) @LIB_SELECT@
test_select_stdin_LDADD = $(LDADD) @LIB_SELECT@
EXTRA_DIST += macros.h signature.h test-select.c test-select.h test-select-fd.c test-select-in.sh test-select-out.sh test-select-stdin.c

## end   gnulib module select-tests

## begin gnulib module send-tests

GNULIB_TESTS += test-send
check_PROGRAMS += test-send
test_send_LDADD = $(LDADD) @LIBSOCKET@
EXTRA_DIST += test-send.c signature.h macros.h

## end   gnulib module send-tests

## begin gnulib module setenv-tests

GNULIB_TESTS += test-setenv
check_PROGRAMS += test-setenv
EXTRA_DIST += test-setenv.c signature.h macros.h

## end   gnulib module setenv-tests

## begin gnulib module setlocale


EXTRA_DIST += setlocale.c

EXTRA_libtests_a_SOURCES += setlocale.c

## end   gnulib module setlocale

## begin gnulib module setlocale-tests

GNULIB_TESTS += test-setlocale1.sh test-setlocale2.sh
TESTS_ENVIRONMENT += \
  LOCALE_FR='@LOCALE_FR@' \
  LOCALE_FR_UTF8='@LOCALE_FR_UTF8@' \
  LOCALE_JA='@LOCALE_JA@' \
  LOCALE_ZH_CN='@LOCALE_ZH_CN@'
check_PROGRAMS += test-setlocale1 test-setlocale2
EXTRA_DIST += test-setlocale1.sh test-setlocale1.c test-setlocale2.sh test-setlocale2.c signature.h macros.h

## end   gnulib module setlocale-tests

## begin gnulib module setsockopt-tests

GNULIB_TESTS += test-setsockopt
check_PROGRAMS += test-setsockopt
test_setsockopt_LDADD = $(LDADD) @LIBSOCKET@
EXTRA_DIST += test-setsockopt.c signature.h macros.h

## end   gnulib module setsockopt-tests

## begin gnulib module sigaction-tests

GNULIB_TESTS += test-sigaction
check_PROGRAMS += test-sigaction
EXTRA_DIST += test-sigaction.c signature.h macros.h

## end   gnulib module sigaction-tests

## begin gnulib module signal-h-tests

GNULIB_TESTS += test-signal-h
check_PROGRAMS += test-signal-h
EXTRA_DIST += test-signal-h.c

## end   gnulib module signal-h-tests

## begin gnulib module signbit


EXTRA_DIST += float+.h signbitd.c signbitf.c signbitl.c

EXTRA_libtests_a_SOURCES += signbitd.c signbitf.c signbitl.c

## end   gnulib module signbit

## begin gnulib module signbit-tests

GNULIB_TESTS += test-signbit
check_PROGRAMS += test-signbit

EXTRA_DIST += test-signbit.c minus-zero.h infinity.h macros.h

## end   gnulib module signbit-tests

## begin gnulib module sigpipe-tests

GNULIB_TESTS += test-sigpipe.sh
check_PROGRAMS += test-sigpipe

EXTRA_DIST += test-sigpipe.c test-sigpipe.sh macros.h

## end   gnulib module sigpipe-tests

## begin gnulib module sigprocmask-tests

GNULIB_TESTS += test-sigprocmask
check_PROGRAMS += test-sigprocmask
EXTRA_DIST += test-sigprocmask.c signature.h macros.h

## end   gnulib module sigprocmask-tests

## begin gnulib module sleep-tests

GNULIB_TESTS += test-sleep
check_PROGRAMS += test-sleep
EXTRA_DIST += test-sleep.c signature.h macros.h

## end   gnulib module sleep-tests

## begin gnulib module snippet/_Noreturn

# Because this Makefile snippet defines a variable used by other
# gnulib Makefile snippets, it must be present in all makefiles that
# need it. This is ensured by the applicability 'all' defined above.

_NORETURN_H=$(srcdir)/_Noreturn.h

EXTRA_DIST += _Noreturn.h

## end   gnulib module snippet/_Noreturn

## begin gnulib module snippet/arg-nonnull

# Because this Makefile snippet defines a variable used by other
# gnulib Makefile snippets, it must be present in all makefiles that
# need it. This is ensured by the applicability 'all' defined above.

ARG_NONNULL_H=$(srcdir)/arg-nonnull.h

EXTRA_DIST += arg-nonnull.h

## end   gnulib module snippet/arg-nonnull

## begin gnulib module snippet/c++defs

# Because this Makefile snippet defines a variable used by other
# gnulib Makefile snippets, it must be present in all makefiles that
# need it. This is ensured by the applicability 'all' defined above.

CXXDEFS_H=$(srcdir)/c++defs.h

EXTRA_DIST += c++defs.h

## end   gnulib module snippet/c++defs

## begin gnulib module snippet/unused-parameter

# Because this Makefile snippet defines a variable used by other
# gnulib Makefile snippets, it must be present in all makefiles that
# need it. This is ensured by the applicability 'all' defined above.

UNUSED_PARAMETER_H=$(srcdir)/unused-parameter.h

EXTRA_DIST += unused-parameter.h

## end   gnulib module snippet/unused-parameter

## begin gnulib module snippet/warn-on-use

# Because this Makefile snippet defines a variable used by other
# gnulib Makefile snippets, it must be present in all makefiles that
# need it. This is ensured by the applicability 'all' defined above.

WARN_ON_USE_H=$(srcdir)/warn-on-use.h

EXTRA_DIST += warn-on-use.h

## end   gnulib module snippet/warn-on-use

## begin gnulib module snprintf-tests

GNULIB_TESTS += test-snprintf
check_PROGRAMS += test-snprintf

EXTRA_DIST += test-snprintf.c signature.h macros.h

## end   gnulib module snprintf-tests

## begin gnulib module sockets-tests

GNULIB_TESTS += test-sockets
check_PROGRAMS += test-sockets
test_sockets_LDADD = $(LDADD) @LIBSOCKET@
EXTRA_DIST += test-sockets.c

## end   gnulib module sockets-tests

## begin gnulib module spawn

BUILT_SOURCES += spawn.h

# We need the following in order to create a replacement for <spawn.h> when
# the system doesn't have one.
spawn.h: spawn.in.h $(top_builddir)/config.status $(CXXDEFS_H) $(ARG_NONNULL_H) $(WARN_ON_USE_H)
	$(AM_V_GEN)rm -f $@-t $@ && \
	{ echo '/* DO NOT EDIT! GENERATED AUTOMATICALLY! */'; \
	  sed -e 's|@''GUARD_PREFIX''@|GL|g' \
	      -e 's|@''HAVE_SPAWN_H''@|$(HAVE_SPAWN_H)|g' \
	      -e 's|@''INCLUDE_NEXT''@|$(INCLUDE_NEXT)|g' \
	      -e 's|@''PRAGMA_SYSTEM_HEADER''@|@PRAGMA_SYSTEM_HEADER@|g' \
	      -e 's|@''PRAGMA_COLUMNS''@|@PRAGMA_COLUMNS@|g' \
	      -e 's|@''NEXT_SPAWN_H''@|$(NEXT_SPAWN_H)|g' \
	      -e 's/@''GNULIB_POSIX_SPAWN''@/$(GNULIB_POSIX_SPAWN)/g' \
	      -e 's/@''GNULIB_POSIX_SPAWNP''@/$(GNULIB_POSIX_SPAWNP)/g' \
	      -e 's/@''GNULIB_POSIX_SPAWN_FILE_ACTIONS_INIT''@/$(GNULIB_POSIX_SPAWN_FILE_ACTIONS_INIT)/g' \
	      -e 's/@''GNULIB_POSIX_SPAWN_FILE_ACTIONS_ADDCLOSE''@/$(GNULIB_POSIX_SPAWN_FILE_ACTIONS_ADDCLOSE)/g' \
	      -e 's/@''GNULIB_POSIX_SPAWN_FILE_ACTIONS_ADDDUP2''@/$(GNULIB_POSIX_SPAWN_FILE_ACTIONS_ADDDUP2)/g' \
	      -e 's/@''GNULIB_POSIX_SPAWN_FILE_ACTIONS_ADDOPEN''@/$(GNULIB_POSIX_SPAWN_FILE_ACTIONS_ADDOPEN)/g' \
	      -e 's/@''GNULIB_POSIX_SPAWN_FILE_ACTIONS_DESTROY''@/$(GNULIB_POSIX_SPAWN_FILE_ACTIONS_DESTROY)/g' \
	      -e 's/@''GNULIB_POSIX_SPAWNATTR_INIT''@/$(GNULIB_POSIX_SPAWNATTR_INIT)/g' \
	      -e 's/@''GNULIB_POSIX_SPAWNATTR_GETFLAGS''@/$(GNULIB_POSIX_SPAWNATTR_GETFLAGS)/g' \
	      -e 's/@''GNULIB_POSIX_SPAWNATTR_SETFLAGS''@/$(GNULIB_POSIX_SPAWNATTR_SETFLAGS)/g' \
	      -e 's/@''GNULIB_POSIX_SPAWNATTR_GETPGROUP''@/$(GNULIB_POSIX_SPAWNATTR_GETPGROUP)/g' \
	      -e 's/@''GNULIB_POSIX_SPAWNATTR_SETPGROUP''@/$(GNULIB_POSIX_SPAWNATTR_SETPGROUP)/g' \
	      -e 's/@''GNULIB_POSIX_SPAWNATTR_GETSCHEDPARAM''@/$(GNULIB_POSIX_SPAWNATTR_GETSCHEDPARAM)/g' \
	      -e 's/@''GNULIB_POSIX_SPAWNATTR_SETSCHEDPARAM''@/$(GNULIB_POSIX_SPAWNATTR_SETSCHEDPARAM)/g' \
	      -e 's/@''GNULIB_POSIX_SPAWNATTR_GETSCHEDPOLICY''@/$(GNULIB_POSIX_SPAWNATTR_GETSCHEDPOLICY)/g' \
	      -e 's/@''GNULIB_POSIX_SPAWNATTR_SETSCHEDPOLICY''@/$(GNULIB_POSIX_SPAWNATTR_SETSCHEDPOLICY)/g' \
	      -e 's/@''GNULIB_POSIX_SPAWNATTR_GETSIGDEFAULT''@/$(GNULIB_POSIX_SPAWNATTR_GETSIGDEFAULT)/g' \
	      -e 's/@''GNULIB_POSIX_SPAWNATTR_SETSIGDEFAULT''@/$(GNULIB_POSIX_SPAWNATTR_SETSIGDEFAULT)/g' \
	      -e 's/@''GNULIB_POSIX_SPAWNATTR_GETSIGMASK''@/$(GNULIB_POSIX_SPAWNATTR_GETSIGMASK)/g' \
	      -e 's/@''GNULIB_POSIX_SPAWNATTR_SETSIGMASK''@/$(GNULIB_POSIX_SPAWNATTR_SETSIGMASK)/g' \
	      -e 's/@''GNULIB_POSIX_SPAWNATTR_DESTROY''@/$(GNULIB_POSIX_SPAWNATTR_DESTROY)/g' \
	      -e 's|@''HAVE_POSIX_SPAWN''@|$(HAVE_POSIX_SPAWN)|g' \
	      -e 's|@''HAVE_POSIX_SPAWNATTR_T''@|$(HAVE_POSIX_SPAWNATTR_T)|g' \
	      -e 's|@''HAVE_POSIX_SPAWN_FILE_ACTIONS_T''@|$(HAVE_POSIX_SPAWN_FILE_ACTIONS_T)|g' \
	      -e 's|@''REPLACE_POSIX_SPAWN''@|$(REPLACE_POSIX_SPAWN)|g' \
	      -e 's|@''REPLACE_POSIX_SPAWN_FILE_ACTIONS_ADDCLOSE''@|$(REPLACE_POSIX_SPAWN_FILE_ACTIONS_ADDCLOSE)|g' \
	      -e 's|@''REPLACE_POSIX_SPAWN_FILE_ACTIONS_ADDDUP2''@|$(REPLACE_POSIX_SPAWN_FILE_ACTIONS_ADDDUP2)|g' \
	      -e 's|@''REPLACE_POSIX_SPAWN_FILE_ACTIONS_ADDOPEN''@|$(REPLACE_POSIX_SPAWN_FILE_ACTIONS_ADDOPEN)|g' \
	      -e '/definitions of _GL_FUNCDECL_RPL/r $(CXXDEFS_H)' \
	      -e '/definition of _GL_ARG_NONNULL/r $(ARG_NONNULL_H)' \
	      -e '/definition of _GL_WARN_ON_USE/r $(WARN_ON_USE_H)' \
	      < $(srcdir)/spawn.in.h; \
	} > $@-t && \
	mv $@-t $@
MOSTLYCLEANFILES += spawn.h spawn.h-t

EXTRA_DIST += spawn.in.h

## end   gnulib module spawn

## begin gnulib module spawn-tests

GNULIB_TESTS += test-spawn
check_PROGRAMS += test-spawn
EXTRA_DIST += test-spawn.c

## end   gnulib module spawn-tests

## begin gnulib module stat-tests

GNULIB_TESTS += test-stat
check_PROGRAMS += test-stat
test_stat_LDADD = $(LDADD) $(LIBINTL)
EXTRA_DIST += test-stat.h test-stat.c signature.h macros.h

## end   gnulib module stat-tests

## begin gnulib module stat-time-tests

GNULIB_TESTS += test-stat-time
check_PROGRAMS += test-stat-time
test_stat_time_LDADD = $(LDADD) $(LIB_NANOSLEEP)
EXTRA_DIST += test-stat-time.c macros.h nap.h

## end   gnulib module stat-time-tests

## begin gnulib module stdalign-tests

GNULIB_TESTS += test-stdalign
check_PROGRAMS += test-stdalign
EXTRA_DIST += test-stdalign.c macros.h

## end   gnulib module stdalign-tests

## begin gnulib module stdbool-tests

GNULIB_TESTS += test-stdbool
check_PROGRAMS += test-stdbool
EXTRA_DIST += test-stdbool.c

## end   gnulib module stdbool-tests

## begin gnulib module stddef-tests

GNULIB_TESTS += test-stddef
check_PROGRAMS += test-stddef
EXTRA_DIST += test-stddef.c

## end   gnulib module stddef-tests

## begin gnulib module stdint-tests

GNULIB_TESTS += test-stdint
check_PROGRAMS += test-stdint
EXTRA_DIST += test-stdint.c

## end   gnulib module stdint-tests

## begin gnulib module stdio-tests

GNULIB_TESTS += test-stdio
check_PROGRAMS += test-stdio
EXTRA_DIST += test-stdio.c

## end   gnulib module stdio-tests

## begin gnulib module stdlib-tests

GNULIB_TESTS += test-stdlib
check_PROGRAMS += test-stdlib
EXTRA_DIST += test-stdlib.c test-sys_wait.h

## end   gnulib module stdlib-tests

## begin gnulib module strchrnul-tests

GNULIB_TESTS += test-strchrnul
check_PROGRAMS += test-strchrnul
EXTRA_DIST += test-strchrnul.c signature.h macros.h

## end   gnulib module strchrnul-tests

## begin gnulib module strerror-tests

GNULIB_TESTS += test-strerror
check_PROGRAMS += test-strerror
EXTRA_DIST += test-strerror.c signature.h macros.h

## end   gnulib module strerror-tests

## begin gnulib module strerror_r-posix-tests

GNULIB_TESTS += test-strerror_r
check_PROGRAMS += test-strerror_r
EXTRA_DIST += test-strerror_r.c signature.h macros.h

## end   gnulib module strerror_r-posix-tests

## begin gnulib module string-tests

GNULIB_TESTS += test-string
check_PROGRAMS += test-string
EXTRA_DIST += test-string.c

## end   gnulib module string-tests

## begin gnulib module strings-tests

GNULIB_TESTS += test-strings
check_PROGRAMS += test-strings
EXTRA_DIST += test-strings.c

## end   gnulib module strings-tests

## begin gnulib module strnlen-tests

GNULIB_TESTS += test-strnlen
check_PROGRAMS += test-strnlen
EXTRA_DIST += test-strnlen.c zerosize-ptr.h signature.h macros.h

## end   gnulib module strnlen-tests

## begin gnulib module symlink


EXTRA_DIST += symlink.c

EXTRA_libtests_a_SOURCES += symlink.c

## end   gnulib module symlink

## begin gnulib module symlink-tests

GNULIB_TESTS += test-symlink
check_PROGRAMS += test-symlink
EXTRA_DIST += test-symlink.h test-symlink.c signature.h macros.h

## end   gnulib module symlink-tests

## begin gnulib module sys_ioctl-tests

GNULIB_TESTS += test-sys_ioctl
check_PROGRAMS += test-sys_ioctl
EXTRA_DIST += test-sys_ioctl.c

## end   gnulib module sys_ioctl-tests

## begin gnulib module sys_select-tests

GNULIB_TESTS += test-sys_select
check_PROGRAMS += test-sys_select
EXTRA_DIST += test-sys_select.c signature.h

## end   gnulib module sys_select-tests

## begin gnulib module sys_socket-tests

GNULIB_TESTS += test-sys_socket
check_PROGRAMS += test-sys_socket
EXTRA_DIST += test-sys_socket.c

## end   gnulib module sys_socket-tests

## begin gnulib module sys_stat-tests

GNULIB_TESTS += test-sys_stat
check_PROGRAMS += test-sys_stat
EXTRA_DIST += test-sys_stat.c

## end   gnulib module sys_stat-tests

## begin gnulib module sys_time-tests

GNULIB_TESTS += test-sys_time
check_PROGRAMS += test-sys_time
EXTRA_DIST += test-sys_time.c

## end   gnulib module sys_time-tests

## begin gnulib module sys_types-tests

GNULIB_TESTS += test-sys_types
check_PROGRAMS += test-sys_types
EXTRA_DIST += test-sys_types.c

## end   gnulib module sys_types-tests

## begin gnulib module sys_uio-tests

GNULIB_TESTS += test-sys_uio
check_PROGRAMS += test-sys_uio
EXTRA_DIST += test-sys_uio.c

## end   gnulib module sys_uio-tests

## begin gnulib module sys_utsname-tests

GNULIB_TESTS += test-sys_utsname
check_PROGRAMS += test-sys_utsname
EXTRA_DIST += test-sys_utsname.c

## end   gnulib module sys_utsname-tests

## begin gnulib module sys_wait-tests

GNULIB_TESTS += test-sys_wait
check_PROGRAMS += test-sys_wait
EXTRA_DIST += test-sys_wait.c test-sys_wait.h

## end   gnulib module sys_wait-tests

## begin gnulib module termios-tests

GNULIB_TESTS += test-termios
check_PROGRAMS += test-termios
EXTRA_DIST += test-termios.c

## end   gnulib module termios-tests

## begin gnulib module test-framework-sh-tests

GNULIB_TESTS += test-init.sh
EXTRA_DIST += init.sh
EXTRA_DIST += test-init.sh

## end   gnulib module test-framework-sh-tests

## begin gnulib module thread

libtests_a_SOURCES += glthread/thread.h glthread/thread.c

## end   gnulib module thread

## begin gnulib module thread-tests

GNULIB_TESTS += test-thread_self test-thread_create
check_PROGRAMS += test-thread_self test-thread_create
test_thread_self_LDADD = $(LDADD) @LIBTHREAD@
test_thread_create_LDADD = $(LDADD) @LIBMULTITHREAD@
EXTRA_DIST += test-thread_self.c test-thread_create.c macros.h

## end   gnulib module thread-tests

## begin gnulib module time-tests

GNULIB_TESTS += test-time
check_PROGRAMS += test-time
EXTRA_DIST += test-time.c

## end   gnulib module time-tests

## begin gnulib module ttyname_r-tests

GNULIB_TESTS += test-ttyname_r
check_PROGRAMS += test-ttyname_r
EXTRA_DIST += test-ttyname_r.c signature.h macros.h

## end   gnulib module ttyname_r-tests

## begin gnulib module uname-tests

GNULIB_TESTS += test-uname
check_PROGRAMS += test-uname
test_uname_LDADD = $(LDADD) @GETHOSTNAME_LIB@
EXTRA_DIST += test-uname.c signature.h macros.h

## end   gnulib module uname-tests

## begin gnulib module unistd-tests

GNULIB_TESTS += test-unistd
check_PROGRAMS += test-unistd
EXTRA_DIST += test-unistd.c

## end   gnulib module unistd-tests

## begin gnulib module uniwidth/width-tests

GNULIB_TESTS += test-uc_width uniwidth/test-uc_width2.sh
check_PROGRAMS += test-uc_width test-uc_width2
test_uc_width_SOURCES = uniwidth/test-uc_width.c
test_uc_width_LDADD = $(LDADD) $(LIBUNISTRING)
test_uc_width2_SOURCES = uniwidth/test-uc_width2.c
test_uc_width2_LDADD = $(LDADD) $(LIBUNISTRING)
EXTRA_DIST += uniwidth/test-uc_width.c uniwidth/test-uc_width2.c uniwidth/test-uc_width2.sh macros.h

## end   gnulib module uniwidth/width-tests

## begin gnulib module unlockpt


EXTRA_DIST += unlockpt.c

EXTRA_libtests_a_SOURCES += unlockpt.c

## end   gnulib module unlockpt

## begin gnulib module unlockpt-tests

GNULIB_TESTS += test-unlockpt
check_PROGRAMS += test-unlockpt
EXTRA_DIST += test-unlockpt.c signature.h macros.h

## end   gnulib module unlockpt-tests

## begin gnulib module unsetenv-tests

GNULIB_TESTS += test-unsetenv
check_PROGRAMS += test-unsetenv
EXTRA_DIST += test-unsetenv.c signature.h macros.h

## end   gnulib module unsetenv-tests

## begin gnulib module usleep-tests

GNULIB_TESTS += test-usleep
check_PROGRAMS += test-usleep
EXTRA_DIST += test-usleep.c signature.h macros.h

## end   gnulib module usleep-tests

## begin gnulib module vasnprintf-tests

GNULIB_TESTS += test-vasnprintf
check_PROGRAMS += test-vasnprintf

EXTRA_DIST += test-vasnprintf.c macros.h

## end   gnulib module vasnprintf-tests

## begin gnulib module vasprintf-tests

GNULIB_TESTS += test-vasprintf
check_PROGRAMS += test-vasprintf

EXTRA_DIST += test-vasprintf.c signature.h macros.h

## end   gnulib module vasprintf-tests

## begin gnulib module vc-list-files-tests

GNULIB_TESTS += test-vc-list-files-git.sh
GNULIB_TESTS += test-vc-list-files-cvs.sh
TESTS_ENVIRONMENT += abs_aux_dir='$(abs_aux_dir)'
EXTRA_DIST += test-vc-list-files-git.sh test-vc-list-files-cvs.sh

## end   gnulib module vc-list-files-tests

## begin gnulib module verify-tests

TESTS_ENVIRONMENT += MAKE='$(MAKE)'
GNULIB_TESTS += test-verify test-verify.sh
check_PROGRAMS += test-verify
# test-verify-try is never built, but test-verify.sh needs a rule to
# build test-verify-try.o.
EXTRA_PROGRAMS += test-verify-try

# This test expects compilation of test-verify-try.c to fail, and
# each time it fails, the makefile rule does not perform the usual
#  "mv -f $name.Tpo $name.po, so tell make clean to remove that file.
MOSTLYCLEANFILES += .deps/test-verify-try.Tpo
EXTRA_DIST += test-verify.c test-verify-try.c test-verify.sh

## end   gnulib module verify-tests

## begin gnulib module vsnprintf-tests

GNULIB_TESTS += test-vsnprintf
check_PROGRAMS += test-vsnprintf

EXTRA_DIST += test-vsnprintf.c signature.h macros.h

## end   gnulib module vsnprintf-tests

## begin gnulib module wait-process

libtests_a_SOURCES += wait-process.h wait-process.c

## end   gnulib module wait-process

## begin gnulib module wchar-tests

GNULIB_TESTS += test-wchar
check_PROGRAMS += test-wchar
EXTRA_DIST += test-wchar.c

## end   gnulib module wchar-tests

## begin gnulib module wcrtomb-tests

GNULIB_TESTS += \
  test-wcrtomb.sh \
  test-wcrtomb-w32-1.sh test-wcrtomb-w32-2.sh test-wcrtomb-w32-3.sh \
  test-wcrtomb-w32-4.sh test-wcrtomb-w32-5.sh
TESTS_ENVIRONMENT += \
  LOCALE_FR='@LOCALE_FR@' \
  LOCALE_FR_UTF8='@LOCALE_FR_UTF8@' \
  LOCALE_JA='@LOCALE_JA@' \
  LOCALE_ZH_CN='@LOCALE_ZH_CN@'
check_PROGRAMS += test-wcrtomb test-wcrtomb-w32

EXTRA_DIST += test-wcrtomb.sh test-wcrtomb.c test-wcrtomb-w32-1.sh test-wcrtomb-w32-2.sh test-wcrtomb-w32-3.sh test-wcrtomb-w32-4.sh test-wcrtomb-w32-5.sh test-wcrtomb-w32.c signature.h macros.h

## end   gnulib module wcrtomb-tests

## begin gnulib module wctob


EXTRA_DIST += wctob.c

EXTRA_libtests_a_SOURCES += wctob.c

## end   gnulib module wctob

## begin gnulib module wctomb


EXTRA_DIST += wctomb-impl.h wctomb.c

EXTRA_libtests_a_SOURCES += wctomb.c

## end   gnulib module wctomb

## begin gnulib module wctype-h-tests

GNULIB_TESTS += test-wctype-h
check_PROGRAMS += test-wctype-h
EXTRA_DIST += test-wctype-h.c macros.h

## end   gnulib module wctype-h-tests

## begin gnulib module wcwidth-tests

GNULIB_TESTS += test-wcwidth
check_PROGRAMS += test-wcwidth
test_wcwidth_LDADD = $(LDADD) $(LIBUNISTRING)
EXTRA_DIST += test-wcwidth.c signature.h macros.h

## end   gnulib module wcwidth-tests

## begin gnulib module write


EXTRA_DIST += write.c

EXTRA_libtests_a_SOURCES += write.c

## end   gnulib module write

## begin gnulib module write-tests

GNULIB_TESTS += test-write
check_PROGRAMS += test-write
EXTRA_DIST += test-write.c signature.h macros.h

## end   gnulib module write-tests

## begin gnulib module xalloc

libtests_a_SOURCES += xmalloc.c

EXTRA_DIST += xalloc.h

## end   gnulib module xalloc

## begin gnulib module xalloc-die

libtests_a_SOURCES += xalloc-die.c

## end   gnulib module xalloc-die

## begin gnulib module xalloc-die-tests

GNULIB_TESTS += test-xalloc-die.sh
check_PROGRAMS += test-xalloc-die
test_xalloc_die_LDADD = $(LDADD) @LIBINTL@
EXTRA_DIST += test-xalloc-die.c test-xalloc-die.sh

## end   gnulib module xalloc-die-tests

# Clean up after Solaris cc.
clean-local:
	rm -rf SunWS_cache

mostlyclean-local: mostlyclean-generic
	@for dir in '' $(MOSTLYCLEANDIRS); do \
	  if test -n "$$dir" && test -d $$dir; then \
	    echo "rmdir $$dir"; rmdir $$dir; \
	  fi; \
	done; \
	:
