.global cinv_sp
.type cinv,%function
cinv_sp:
#not implemented


.global cinv
.type cinv,%function
cinv:
#not implemented

.global hostcall_asm
.type hostcall_asm,%function
hostcall_asm:
#not implemented

.global st_cap
.type st_cap,%function
st_cap:
#not implemented


.global cinv2
.type cinv2,%function
cinv2:
#not implemented

.global cinv2_sp
.type cinv2,%function
cinv2_sp:
#not implemented



.global ret_from_cinv2
.type ret_from_cinv2,%function
ret_from_cinv2:
#not implemented
