#ifndef CHERI_CAP_PERMS_DEFINITIONS
#define CHERI_CAP_PERMS_DEFINITIONS

#ifndef __CHERI_CAP_PERMISSION_VMEM__
#define __CHERI_CAP_PERMISSION_VMEM__ (1 << 2)
#endif

/**
 * ROOT_CAP_PERMS
 */
#define ROOT_CAP_PERMS \
	__CHERI_CAP_PERMISSION_GLOBAL__ \
	| __CHERI_CAP_PERMISSION_VMEM__

/**
 * READ_CAP_PERMS
 */
#ifdef __ARM_CAP_PERMISSION_MUTABLE_LOAD__
#define READ_CAP_PERMS \
	__ARM_CAP_PERMISSION_MUTABLE_LOAD__ \
	| __CHERI_CAP_PERMISSION_PERMIT_LOAD__ \
	| __CHERI_CAP_PERMISSION_PERMIT_LOAD_CAPABILITY__
#else
#define READ_CAP_PERMS \
	__CHERI_CAP_PERMISSION_PERMIT_LOAD__ \
	| __CHERI_CAP_PERMISSION_PERMIT_LOAD_CAPABILITY__
#endif

/**
 * WRITE_CAP_PERMS
 */
#define WRITE_CAP_PERMS \
	__CHERI_CAP_PERMISSION_PERMIT_STORE__ \
	| __CHERI_CAP_PERMISSION_PERMIT_STORE_CAPABILITY__ \
	| __CHERI_CAP_PERMISSION_PERMIT_STORE_LOCAL__

/**
 * EXEC_CAP_PERMS
 */
#ifdef __ARM_CAP_PERMISSION_EXECUTIVE__
#define EXEC_CAP_PERMS \
	__ARM_CAP_PERMISSION_EXECUTIVE__ \
	| __CHERI_CAP_PERMISSION_PERMIT_EXECUTE__ \
	| __CHERI_CAP_PERMISSION_ACCESS_SYSTEM_REGISTERS__
#else
#define EXEC_CAP_PERMS \
	__CHERI_CAP_PERMISSION_PERMIT_EXECUTE__ \
	| __CHERI_CAP_PERMISSION_ACCESS_SYSTEM_REGISTERS__
#endif

#endif // CHERI_CAP_PERMS_DEFINITIONS